export interface EmojiData {
  emoji: string;
  name: string;
  category: Category;
  keywords: string[];
  codepoint: string;
  hasSkinTone: boolean;
}

export type Category =
  | 'smileys'
  | 'people'
  | 'animals'
  | 'food'
  | 'travel'
  | 'activities'
  | 'objects'
  | 'symbols'
  | 'flags';

export const CATEGORY_INFO: Record<Category, { label: string; icon: string }> = {
  smileys: { label: 'Smileys & Emotion', icon: '😀' },
  people: { label: 'People & Body', icon: '👋' },
  animals: { label: 'Animals & Nature', icon: '🐶' },
  food: { label: 'Food & Drink', icon: '🍕' },
  travel: { label: 'Travel & Places', icon: '✈️' },
  activities: { label: 'Activities', icon: '⚽' },
  objects: { label: 'Objects', icon: '💡' },
  symbols: { label: 'Symbols', icon: '❤️' },
  flags: { label: 'Flags', icon: '🏁' },
};

export const CATEGORIES: Category[] = [
  'smileys', 'people', 'animals', 'food', 'travel', 'activities', 'objects', 'symbols', 'flags',
];

export const SKIN_TONES = [
  { modifier: '', label: 'Default', preview: '👋' },
  { modifier: '\u{1F3FB}', label: 'Light', preview: '👋🏻' },
  { modifier: '\u{1F3FC}', label: 'Medium-Light', preview: '👋🏼' },
  { modifier: '\u{1F3FD}', label: 'Medium', preview: '👋🏽' },
  { modifier: '\u{1F3FE}', label: 'Medium-Dark', preview: '👋🏾' },
  { modifier: '\u{1F3FF}', label: 'Dark', preview: '👋🏿' },
];

function e(emoji: string, name: string, category: Category, keywords: string[], hasSkinTone = false): EmojiData {
  const codepoint = [...emoji].map(c => 'U+' + c.codePointAt(0)!.toString(16).toUpperCase().padStart(4, '0')).join(' ');
  return { emoji, name, category, keywords, codepoint, hasSkinTone };
}

export const EMOJIS: EmojiData[] = [
  // ===== SMILEYS & EMOTION =====
  e('😀', 'Grinning Face', 'smileys', ['happy', 'smile', 'grin', 'joy']),
  e('😃', 'Grinning Face with Big Eyes', 'smileys', ['happy', 'smile', 'excited']),
  e('😄', 'Grinning Face with Smiling Eyes', 'smileys', ['happy', 'laugh', 'joy']),
  e('😁', 'Beaming Face with Smiling Eyes', 'smileys', ['grin', 'happy', 'beam']),
  e('😆', 'Grinning Squinting Face', 'smileys', ['laugh', 'happy', 'lol']),
  e('😅', 'Grinning Face with Sweat', 'smileys', ['nervous', 'relief', 'phew']),
  e('🤣', 'Rolling on the Floor Laughing', 'smileys', ['rofl', 'lol', 'laugh', 'funny']),
  e('😂', 'Face with Tears of Joy', 'smileys', ['laugh', 'cry', 'happy', 'lol', 'funny']),
  e('🙂', 'Slightly Smiling Face', 'smileys', ['smile', 'ok', 'neutral']),
  e('🙃', 'Upside-Down Face', 'smileys', ['sarcasm', 'silly', 'ironic']),
  e('😉', 'Winking Face', 'smileys', ['wink', 'flirt', 'playful']),
  e('😊', 'Smiling Face with Smiling Eyes', 'smileys', ['blush', 'happy', 'warm']),
  e('😇', 'Smiling Face with Halo', 'smileys', ['angel', 'innocent', 'good']),
  e('🥰', 'Smiling Face with Hearts', 'smileys', ['love', 'adore', 'hearts', 'affection']),
  e('😍', 'Smiling Face with Heart-Eyes', 'smileys', ['love', 'crush', 'hearts', 'adore']),
  e('🤩', 'Star-Struck', 'smileys', ['excited', 'wow', 'star', 'amazing']),
  e('😘', 'Face Blowing a Kiss', 'smileys', ['kiss', 'love', 'flirt']),
  e('😗', 'Kissing Face', 'smileys', ['kiss', 'whistle']),
  e('😚', 'Kissing Face with Closed Eyes', 'smileys', ['kiss', 'love']),
  e('😙', 'Kissing Face with Smiling Eyes', 'smileys', ['kiss', 'happy']),
  e('🥲', 'Smiling Face with Tear', 'smileys', ['happy', 'sad', 'bittersweet', 'grateful']),
  e('😋', 'Face Savoring Food', 'smileys', ['yum', 'delicious', 'tasty']),
  e('😛', 'Face with Tongue', 'smileys', ['tongue', 'playful', 'silly']),
  e('😜', 'Winking Face with Tongue', 'smileys', ['tongue', 'wink', 'silly', 'playful']),
  e('🤪', 'Zany Face', 'smileys', ['crazy', 'wild', 'silly', 'goofy']),
  e('😝', 'Squinting Face with Tongue', 'smileys', ['tongue', 'gross', 'playful']),
  e('🤑', 'Money-Mouth Face', 'smileys', ['money', 'rich', 'dollar']),
  e('🤗', 'Smiling Face with Open Hands', 'smileys', ['hug', 'warm', 'welcome']),
  e('🤭', 'Face with Hand Over Mouth', 'smileys', ['oops', 'giggle', 'shy']),
  e('🤫', 'Shushing Face', 'smileys', ['quiet', 'secret', 'shh']),
  e('🤔', 'Thinking Face', 'smileys', ['think', 'hmm', 'consider', 'wonder']),
  e('🫡', 'Saluting Face', 'smileys', ['salute', 'respect', 'yes sir']),
  e('🤐', 'Zipper-Mouth Face', 'smileys', ['silent', 'secret', 'zip']),
  e('🤨', 'Face with Raised Eyebrow', 'smileys', ['skeptical', 'doubt', 'suspicious']),
  e('😐', 'Neutral Face', 'smileys', ['neutral', 'meh', 'blank']),
  e('😑', 'Expressionless Face', 'smileys', ['blank', 'unimpressed']),
  e('😶', 'Face Without Mouth', 'smileys', ['speechless', 'quiet', 'silent']),
  e('🫥', 'Dotted Line Face', 'smileys', ['invisible', 'hidden', 'disappear']),
  e('😏', 'Smirking Face', 'smileys', ['smirk', 'sly', 'suggestive']),
  e('😒', 'Unamused Face', 'smileys', ['bored', 'annoyed', 'unimpressed']),
  e('🙄', 'Face with Rolling Eyes', 'smileys', ['eyeroll', 'whatever', 'annoyed']),
  e('😬', 'Grimacing Face', 'smileys', ['awkward', 'nervous', 'cringe']),
  e('🤥', 'Lying Face', 'smileys', ['lie', 'pinocchio', 'dishonest']),
  e('🫠', 'Melting Face', 'smileys', ['melt', 'hot', 'embarrassed', 'disappear']),
  e('😌', 'Relieved Face', 'smileys', ['relieved', 'calm', 'peaceful']),
  e('😔', 'Pensive Face', 'smileys', ['sad', 'thoughtful', 'pensive']),
  e('😪', 'Sleepy Face', 'smileys', ['sleepy', 'tired', 'snot']),
  e('🤤', 'Drooling Face', 'smileys', ['drool', 'hungry', 'yum']),
  e('😴', 'Sleeping Face', 'smileys', ['sleep', 'zzz', 'tired']),
  e('😷', 'Face with Medical Mask', 'smileys', ['mask', 'sick', 'ill', 'covid']),
  e('🤒', 'Face with Thermometer', 'smileys', ['sick', 'fever', 'ill']),
  e('🤕', 'Face with Head-Bandage', 'smileys', ['hurt', 'injured', 'ouch']),
  e('🤢', 'Nauseated Face', 'smileys', ['sick', 'nausea', 'green', 'vomit']),
  e('🤮', 'Face Vomiting', 'smileys', ['vomit', 'sick', 'puke', 'gross']),
  e('🥵', 'Hot Face', 'smileys', ['hot', 'sweating', 'heat']),
  e('🥶', 'Cold Face', 'smileys', ['cold', 'freezing', 'ice']),
  e('🥴', 'Woozy Face', 'smileys', ['dizzy', 'drunk', 'woozy']),
  e('😵', 'Face with Crossed-Out Eyes', 'smileys', ['dizzy', 'dead', 'shocked']),
  e('🤯', 'Exploding Head', 'smileys', ['mind blown', 'shocked', 'wow', 'amazed']),
  e('🤠', 'Cowboy Hat Face', 'smileys', ['cowboy', 'western', 'yeehaw']),
  e('🥳', 'Partying Face', 'smileys', ['party', 'celebrate', 'birthday', 'hooray']),
  e('🥸', 'Disguised Face', 'smileys', ['disguise', 'incognito', 'glasses']),
  e('😎', 'Smiling Face with Sunglasses', 'smileys', ['cool', 'sunglasses', 'chill']),
  e('🤓', 'Nerd Face', 'smileys', ['nerd', 'geek', 'smart', 'glasses']),
  e('🧐', 'Face with Monocle', 'smileys', ['monocle', 'fancy', 'inspect', 'hmm']),
  e('😕', 'Confused Face', 'smileys', ['confused', 'uncertain', 'puzzled']),
  e('🫤', 'Face with Diagonal Mouth', 'smileys', ['skeptical', 'unsure', 'meh']),
  e('😟', 'Worried Face', 'smileys', ['worried', 'concerned', 'anxious']),
  e('🙁', 'Slightly Frowning Face', 'smileys', ['frown', 'sad', 'disappointed']),
  e('😮', 'Face with Open Mouth', 'smileys', ['surprised', 'oh', 'wow']),
  e('😯', 'Hushed Face', 'smileys', ['surprised', 'hushed', 'quiet']),
  e('😲', 'Astonished Face', 'smileys', ['astonished', 'shocked', 'wow']),
  e('😳', 'Flushed Face', 'smileys', ['embarrassed', 'blush', 'shy']),
  e('🥺', 'Pleading Face', 'smileys', ['puppy eyes', 'please', 'beg', 'cute']),
  e('🥹', 'Face Holding Back Tears', 'smileys', ['emotional', 'touched', 'proud', 'grateful']),
  e('😦', 'Frowning Face with Open Mouth', 'smileys', ['frown', 'aw', 'sad']),
  e('😧', 'Anguished Face', 'smileys', ['anguish', 'pain', 'upset']),
  e('😨', 'Fearful Face', 'smileys', ['scared', 'fear', 'afraid']),
  e('😰', 'Anxious Face with Sweat', 'smileys', ['anxious', 'nervous', 'worried']),
  e('😥', 'Sad but Relieved Face', 'smileys', ['sad', 'relieved', 'disappointed']),
  e('😢', 'Crying Face', 'smileys', ['cry', 'sad', 'tear']),
  e('😭', 'Loudly Crying Face', 'smileys', ['cry', 'sob', 'sad', 'wail']),
  e('😱', 'Face Screaming in Fear', 'smileys', ['scream', 'horror', 'scared', 'shock']),
  e('😖', 'Confounded Face', 'smileys', ['frustrated', 'upset', 'confused']),
  e('😣', 'Persevering Face', 'smileys', ['struggle', 'persevere', 'tired']),
  e('😞', 'Disappointed Face', 'smileys', ['sad', 'disappointed', 'down']),
  e('😓', 'Downcast Face with Sweat', 'smileys', ['tired', 'frustrated', 'hard work']),
  e('😩', 'Weary Face', 'smileys', ['tired', 'weary', 'frustrated']),
  e('😫', 'Tired Face', 'smileys', ['tired', 'exhausted', 'whine']),
  e('🥱', 'Yawning Face', 'smileys', ['yawn', 'tired', 'bored', 'sleepy']),
  e('😤', 'Face with Steam from Nose', 'smileys', ['angry', 'frustrated', 'triumph']),
  e('😡', 'Pouting Face', 'smileys', ['angry', 'mad', 'rage', 'furious']),
  e('😠', 'Angry Face', 'smileys', ['angry', 'mad', 'grumpy']),
  e('🤬', 'Face with Symbols on Mouth', 'smileys', ['swear', 'curse', 'angry']),
  e('😈', 'Smiling Face with Horns', 'smileys', ['devil', 'evil', 'mischief']),
  e('👿', 'Angry Face with Horns', 'smileys', ['devil', 'angry', 'evil']),
  e('💀', 'Skull', 'smileys', ['death', 'dead', 'skeleton', 'danger']),
  e('☠️', 'Skull and Crossbones', 'smileys', ['death', 'danger', 'poison', 'pirate']),
  e('💩', 'Pile of Poo', 'smileys', ['poop', 'crap', 'funny']),
  e('🤡', 'Clown Face', 'smileys', ['clown', 'circus', 'funny', 'fool']),
  e('👹', 'Ogre', 'smileys', ['monster', 'ogre', 'japanese']),
  e('👺', 'Goblin', 'smileys', ['goblin', 'tengu', 'japanese']),
  e('👻', 'Ghost', 'smileys', ['ghost', 'halloween', 'spooky', 'boo']),
  e('👽', 'Alien', 'smileys', ['alien', 'ufo', 'space', 'extraterrestrial']),
  e('👾', 'Alien Monster', 'smileys', ['game', 'space invader', 'pixel', 'retro']),
  e('🤖', 'Robot', 'smileys', ['robot', 'ai', 'machine', 'tech']),
  e('😺', 'Grinning Cat', 'smileys', ['cat', 'happy', 'smile']),
  e('😸', 'Grinning Cat with Smiling Eyes', 'smileys', ['cat', 'happy']),
  e('😹', 'Cat with Tears of Joy', 'smileys', ['cat', 'laugh', 'happy']),
  e('😻', 'Smiling Cat with Heart-Eyes', 'smileys', ['cat', 'love', 'heart']),
  e('😼', 'Cat with Wry Smile', 'smileys', ['cat', 'smirk', 'sly']),
  e('😽', 'Kissing Cat', 'smileys', ['cat', 'kiss', 'love']),
  e('🙀', 'Weary Cat', 'smileys', ['cat', 'shocked', 'surprised']),
  e('😿', 'Crying Cat', 'smileys', ['cat', 'sad', 'cry']),
  e('😾', 'Pouting Cat', 'smileys', ['cat', 'angry', 'grumpy']),
  e('🫶', 'Heart Hands', 'smileys', ['love', 'heart', 'hands', 'care'], true),
  e('💋', 'Kiss Mark', 'smileys', ['kiss', 'lips', 'love']),
  e('💌', 'Love Letter', 'smileys', ['love', 'letter', 'mail', 'heart']),
  e('💘', 'Heart with Arrow', 'smileys', ['love', 'cupid', 'valentine']),
  e('💝', 'Heart with Ribbon', 'smileys', ['love', 'gift', 'valentine']),
  e('💖', 'Sparkling Heart', 'smileys', ['love', 'sparkle', 'shiny']),
  e('💗', 'Growing Heart', 'smileys', ['love', 'growing', 'pink']),
  e('💓', 'Beating Heart', 'smileys', ['love', 'heartbeat', 'pulse']),
  e('💞', 'Revolving Hearts', 'smileys', ['love', 'hearts', 'revolving']),
  e('💕', 'Two Hearts', 'smileys', ['love', 'hearts', 'couple']),
  e('💟', 'Heart Decoration', 'smileys', ['love', 'heart', 'decoration']),
  e('❣️', 'Heart Exclamation', 'smileys', ['love', 'exclamation', 'heart']),
  e('💔', 'Broken Heart', 'smileys', ['heartbreak', 'sad', 'breakup']),
  e('❤️‍🔥', 'Heart on Fire', 'smileys', ['love', 'passion', 'fire', 'desire']),
  e('❤️‍🩹', 'Mending Heart', 'smileys', ['healing', 'recovery', 'love']),
  e('❤️', 'Red Heart', 'smileys', ['love', 'heart', 'red', 'valentine']),
  e('🩷', 'Pink Heart', 'smileys', ['love', 'pink', 'heart']),
  e('🧡', 'Orange Heart', 'smileys', ['love', 'orange', 'heart']),
  e('💛', 'Yellow Heart', 'smileys', ['love', 'yellow', 'heart', 'friendship']),
  e('💚', 'Green Heart', 'smileys', ['love', 'green', 'heart', 'nature']),
  e('💙', 'Blue Heart', 'smileys', ['love', 'blue', 'heart', 'trust']),
  e('🩵', 'Light Blue Heart', 'smileys', ['love', 'light blue', 'heart']),
  e('💜', 'Purple Heart', 'smileys', ['love', 'purple', 'heart']),
  e('🖤', 'Black Heart', 'smileys', ['love', 'black', 'heart', 'dark']),
  e('🩶', 'Grey Heart', 'smileys', ['love', 'grey', 'heart']),
  e('🤍', 'White Heart', 'smileys', ['love', 'white', 'heart', 'pure']),
  e('🤎', 'Brown Heart', 'smileys', ['love', 'brown', 'heart']),
  e('💯', 'Hundred Points', 'smileys', ['perfect', '100', 'score', 'full']),
  e('💢', 'Anger Symbol', 'smileys', ['angry', 'rage', 'symbol']),
  e('💥', 'Collision', 'smileys', ['boom', 'explosion', 'crash', 'bang']),
  e('💫', 'Dizzy', 'smileys', ['star', 'dizzy', 'sparkle']),
  e('💦', 'Sweat Droplets', 'smileys', ['sweat', 'water', 'splash']),
  e('💨', 'Dashing Away', 'smileys', ['wind', 'fast', 'run', 'dash']),
  e('🕳️', 'Hole', 'smileys', ['hole', 'black', 'void']),
  e('💬', 'Speech Balloon', 'smileys', ['speech', 'talk', 'chat', 'message']),
  e('💭', 'Thought Balloon', 'smileys', ['thought', 'think', 'bubble']),
  e('🗯️', 'Right Anger Bubble', 'smileys', ['anger', 'speech', 'yell']),
  e('💤', 'Zzz', 'smileys', ['sleep', 'zzz', 'tired', 'snore']),

  // ===== PEOPLE & BODY =====
  e('👋', 'Waving Hand', 'people', ['wave', 'hello', 'goodbye', 'hi'], true),
  e('🤚', 'Raised Back of Hand', 'people', ['hand', 'raised', 'stop'], true),
  e('🖐️', 'Hand with Fingers Splayed', 'people', ['hand', 'five', 'high five'], true),
  e('✋', 'Raised Hand', 'people', ['hand', 'stop', 'high five'], true),
  e('🖖', 'Vulcan Salute', 'people', ['spock', 'vulcan', 'star trek'], true),
  e('🫱', 'Rightwards Hand', 'people', ['hand', 'right', 'handshake'], true),
  e('🫲', 'Leftwards Hand', 'people', ['hand', 'left', 'handshake'], true),
  e('🫳', 'Palm Down Hand', 'people', ['hand', 'drop', 'dismiss'], true),
  e('🫴', 'Palm Up Hand', 'people', ['hand', 'offer', 'catch'], true),
  e('👌', 'OK Hand', 'people', ['ok', 'perfect', 'good', 'nice'], true),
  e('🤌', 'Pinched Fingers', 'people', ['italian', 'what', 'gesture', 'chef kiss'], true),
  e('🤏', 'Pinching Hand', 'people', ['small', 'little', 'tiny', 'pinch'], true),
  e('✌️', 'Victory Hand', 'people', ['peace', 'victory', 'two'], true),
  e('🤞', 'Crossed Fingers', 'people', ['luck', 'hope', 'fingers crossed'], true),
  e('🫰', 'Hand with Index Finger and Thumb Crossed', 'people', ['money', 'snap', 'love'], true),
  e('🤟', 'Love-You Gesture', 'people', ['love', 'ily', 'rock'], true),
  e('🤘', 'Sign of the Horns', 'people', ['rock', 'metal', 'horns'], true),
  e('🤙', 'Call Me Hand', 'people', ['call', 'shaka', 'hang loose'], true),
  e('👈', 'Backhand Index Pointing Left', 'people', ['left', 'point', 'direction'], true),
  e('👉', 'Backhand Index Pointing Right', 'people', ['right', 'point', 'direction'], true),
  e('👆', 'Backhand Index Pointing Up', 'people', ['up', 'point', 'direction'], true),
  e('🖕', 'Middle Finger', 'people', ['middle finger', 'rude', 'angry'], true),
  e('👇', 'Backhand Index Pointing Down', 'people', ['down', 'point', 'direction'], true),
  e('☝️', 'Index Pointing Up', 'people', ['point', 'up', 'one'], true),
  e('🫵', 'Index Pointing at the Viewer', 'people', ['point', 'you', 'uncle sam'], true),
  e('👍', 'Thumbs Up', 'people', ['like', 'approve', 'good', 'yes', 'ok'], true),
  e('👎', 'Thumbs Down', 'people', ['dislike', 'bad', 'no', 'disapprove'], true),
  e('✊', 'Raised Fist', 'people', ['fist', 'power', 'punch'], true),
  e('👊', 'Oncoming Fist', 'people', ['fist bump', 'punch', 'power'], true),
  e('🤛', 'Left-Facing Fist', 'people', ['fist bump', 'left'], true),
  e('🤜', 'Right-Facing Fist', 'people', ['fist bump', 'right'], true),
  e('👏', 'Clapping Hands', 'people', ['clap', 'applause', 'bravo', 'congrats'], true),
  e('🙌', 'Raising Hands', 'people', ['celebration', 'hooray', 'praise', 'hands up'], true),
  e('🫶', 'Heart Hands', 'people', ['love', 'heart', 'hands', 'care'], true),
  e('👐', 'Open Hands', 'people', ['hands', 'open', 'jazz'], true),
  e('🤲', 'Palms Up Together', 'people', ['prayer', 'palms', 'ask'], true),
  e('🤝', 'Handshake', 'people', ['handshake', 'deal', 'agreement']),
  e('🙏', 'Folded Hands', 'people', ['pray', 'please', 'thank you', 'namaste', 'hope'], true),
  e('✍️', 'Writing Hand', 'people', ['write', 'pen', 'note'], true),
  e('💅', 'Nail Polish', 'people', ['nails', 'beauty', 'manicure', 'sassy'], true),
  e('🤳', 'Selfie', 'people', ['selfie', 'camera', 'photo'], true),
  e('💪', 'Flexed Biceps', 'people', ['strong', 'muscle', 'flex', 'power', 'gym'], true),
  e('🦾', 'Mechanical Arm', 'people', ['prosthetic', 'robot', 'strong']),
  e('🦿', 'Mechanical Leg', 'people', ['prosthetic', 'robot']),
  e('🦵', 'Leg', 'people', ['leg', 'kick', 'limb'], true),
  e('🦶', 'Foot', 'people', ['foot', 'kick', 'stomp'], true),
  e('👂', 'Ear', 'people', ['ear', 'hear', 'listen', 'sound'], true),
  e('🦻', 'Ear with Hearing Aid', 'people', ['hearing', 'accessibility', 'deaf'], true),
  e('👃', 'Nose', 'people', ['nose', 'smell', 'sniff'], true),
  e('🧠', 'Brain', 'people', ['brain', 'smart', 'think', 'mind']),
  e('🫀', 'Anatomical Heart', 'people', ['heart', 'organ', 'cardiology']),
  e('🫁', 'Lungs', 'people', ['lungs', 'breathe', 'respiratory']),
  e('🦷', 'Tooth', 'people', ['tooth', 'dental', 'dentist']),
  e('🦴', 'Bone', 'people', ['bone', 'skeleton']),
  e('👀', 'Eyes', 'people', ['eyes', 'look', 'see', 'watch', 'stare']),
  e('👁️', 'Eye', 'people', ['eye', 'look', 'see']),
  e('👅', 'Tongue', 'people', ['tongue', 'taste', 'lick']),
  e('👄', 'Mouth', 'people', ['mouth', 'lips', 'kiss']),
  e('🫦', 'Biting Lip', 'people', ['lip', 'bite', 'nervous', 'flirt']),
  e('👶', 'Baby', 'people', ['baby', 'infant', 'child', 'newborn'], true),
  e('🧒', 'Child', 'people', ['child', 'kid', 'young'], true),
  e('👦', 'Boy', 'people', ['boy', 'male', 'child'], true),
  e('👧', 'Girl', 'people', ['girl', 'female', 'child'], true),
  e('🧑', 'Person', 'people', ['person', 'adult', 'gender neutral'], true),
  e('👱', 'Person: Blond Hair', 'people', ['blond', 'blonde', 'hair'], true),
  e('👨', 'Man', 'people', ['man', 'male', 'guy', 'boy'], true),
  e('🧔', 'Person: Beard', 'people', ['beard', 'facial hair'], true),
  e('👩', 'Woman', 'people', ['woman', 'female', 'girl', 'lady'], true),
  e('🧓', 'Older Person', 'people', ['old', 'elder', 'senior'], true),
  e('👴', 'Old Man', 'people', ['old man', 'grandpa', 'elder'], true),
  e('👵', 'Old Woman', 'people', ['old woman', 'grandma', 'elder'], true),
  e('🙍', 'Person Frowning', 'people', ['frown', 'sad', 'disappointed'], true),
  e('🙎', 'Person Pouting', 'people', ['pouting', 'angry', 'upset'], true),
  e('🙅', 'Person Gesturing No', 'people', ['no', 'stop', 'deny'], true),
  e('🙆', 'Person Gesturing OK', 'people', ['ok', 'yes', 'approve'], true),
  e('💁', 'Person Tipping Hand', 'people', ['info', 'sassy', 'help'], true),
  e('🙋', 'Person Raising Hand', 'people', ['hand', 'question', 'volunteer'], true),
  e('🧏', 'Deaf Person', 'people', ['deaf', 'hearing', 'accessibility'], true),
  e('🙇', 'Person Bowing', 'people', ['bow', 'sorry', 'respect'], true),
  e('🤦', 'Person Facepalming', 'people', ['facepalm', 'disbelief', 'smh'], true),
  e('🤷', 'Person Shrugging', 'people', ['shrug', 'idk', 'whatever', 'dunno'], true),
  e('👮', 'Police Officer', 'people', ['police', 'cop', 'law', 'officer'], true),
  e('🕵️', 'Detective', 'people', ['detective', 'spy', 'investigate'], true),
  e('💂', 'Guard', 'people', ['guard', 'soldier', 'british'], true),
  e('🥷', 'Ninja', 'people', ['ninja', 'stealth', 'hidden']),
  e('👷', 'Construction Worker', 'people', ['construction', 'worker', 'build'], true),
  e('🫅', 'Person with Crown', 'people', ['royalty', 'monarch', 'crown'], true),
  e('🤴', 'Prince', 'people', ['prince', 'royal', 'king'], true),
  e('👸', 'Princess', 'people', ['princess', 'royal', 'queen'], true),
  e('👳', 'Person Wearing Turban', 'people', ['turban', 'indian'], true),
  e('👲', 'Person with Skullcap', 'people', ['gua pi mao', 'chinese'], true),
  e('🧕', 'Woman with Headscarf', 'people', ['hijab', 'headscarf', 'modest'], true),
  e('🤵', 'Person in Tuxedo', 'people', ['tuxedo', 'formal', 'groom'], true),
  e('👰', 'Person with Veil', 'people', ['bride', 'wedding', 'veil'], true),
  e('🤰', 'Pregnant Woman', 'people', ['pregnant', 'baby', 'expecting'], true),
  e('🫃', 'Pregnant Man', 'people', ['pregnant', 'belly'], true),
  e('🫄', 'Pregnant Person', 'people', ['pregnant', 'belly', 'expecting'], true),
  e('🤱', 'Breast-Feeding', 'people', ['breastfeed', 'nursing', 'baby'], true),
  e('👼', 'Baby Angel', 'people', ['angel', 'baby', 'cherub'], true),
  e('🎅', 'Santa Claus', 'people', ['santa', 'christmas', 'holiday'], true),
  e('🤶', 'Mrs. Claus', 'people', ['christmas', 'mrs claus', 'holiday'], true),
  e('🦸', 'Superhero', 'people', ['superhero', 'hero', 'power'], true),
  e('🦹', 'Supervillain', 'people', ['villain', 'evil', 'bad'], true),
  e('🧙', 'Mage', 'people', ['wizard', 'mage', 'magic'], true),
  e('🧚', 'Fairy', 'people', ['fairy', 'magic', 'fantasy'], true),
  e('🧛', 'Vampire', 'people', ['vampire', 'dracula', 'halloween'], true),
  e('🧜', 'Merperson', 'people', ['mermaid', 'merman', 'sea'], true),
  e('🧝', 'Elf', 'people', ['elf', 'fantasy', 'lord of the rings'], true),
  e('🧞', 'Genie', 'people', ['genie', 'lamp', 'wish']),
  e('🧟', 'Zombie', 'people', ['zombie', 'undead', 'walking dead']),
  e('🧌', 'Troll', 'people', ['troll', 'fairy tale', 'fantasy']),
  e('💏', 'Kiss', 'people', ['kiss', 'couple', 'love']),
  e('💑', 'Couple with Heart', 'people', ['love', 'couple', 'heart']),
  e('👪', 'Family', 'people', ['family', 'parents', 'child']),
  e('🗣️', 'Speaking Head', 'people', ['speak', 'talk', 'head', 'voice']),
  e('👤', 'Bust in Silhouette', 'people', ['user', 'person', 'profile', 'silhouette']),
  e('👥', 'Busts in Silhouette', 'people', ['users', 'people', 'group', 'team']),
  e('🫂', 'People Hugging', 'people', ['hug', 'embrace', 'comfort']),
  e('👣', 'Footprints', 'people', ['footprints', 'tracks', 'feet', 'walk']),

  // ===== ANIMALS & NATURE =====
  e('🐶', 'Dog Face', 'animals', ['dog', 'puppy', 'pet', 'woof']),
  e('🐱', 'Cat Face', 'animals', ['cat', 'kitten', 'pet', 'meow']),
  e('🐭', 'Mouse Face', 'animals', ['mouse', 'rodent', 'small']),
  e('🐹', 'Hamster', 'animals', ['hamster', 'pet', 'rodent', 'cute']),
  e('🐰', 'Rabbit Face', 'animals', ['rabbit', 'bunny', 'easter']),
  e('🦊', 'Fox', 'animals', ['fox', 'clever', 'animal']),
  e('🐻', 'Bear', 'animals', ['bear', 'teddy', 'animal']),
  e('🐼', 'Panda', 'animals', ['panda', 'bear', 'cute', 'china']),
  e('🐻‍❄️', 'Polar Bear', 'animals', ['polar bear', 'arctic', 'white bear']),
  e('🐨', 'Koala', 'animals', ['koala', 'australia', 'cute']),
  e('🐯', 'Tiger Face', 'animals', ['tiger', 'cat', 'fierce']),
  e('🦁', 'Lion', 'animals', ['lion', 'king', 'jungle', 'brave']),
  e('🐮', 'Cow Face', 'animals', ['cow', 'moo', 'farm']),
  e('🐷', 'Pig Face', 'animals', ['pig', 'oink', 'farm']),
  e('🐸', 'Frog', 'animals', ['frog', 'toad', 'croak', 'kermit']),
  e('🐵', 'Monkey Face', 'animals', ['monkey', 'ape', 'primate']),
  e('🙈', 'See-No-Evil Monkey', 'animals', ['monkey', 'hide', 'shy', 'embarrassed']),
  e('🙉', 'Hear-No-Evil Monkey', 'animals', ['monkey', 'deaf', 'ignore']),
  e('🙊', 'Speak-No-Evil Monkey', 'animals', ['monkey', 'quiet', 'oops']),
  e('🐒', 'Monkey', 'animals', ['monkey', 'primate', 'animal']),
  e('🐔', 'Chicken', 'animals', ['chicken', 'hen', 'poultry', 'farm']),
  e('🐧', 'Penguin', 'animals', ['penguin', 'arctic', 'cold', 'cute']),
  e('🐦', 'Bird', 'animals', ['bird', 'tweet', 'fly']),
  e('🐤', 'Baby Chick', 'animals', ['chick', 'baby', 'bird', 'yellow']),
  e('🐣', 'Hatching Chick', 'animals', ['chick', 'egg', 'hatch', 'baby']),
  e('🐥', 'Front-Facing Baby Chick', 'animals', ['chick', 'baby', 'bird']),
  e('🦆', 'Duck', 'animals', ['duck', 'quack', 'bird']),
  e('🦅', 'Eagle', 'animals', ['eagle', 'bird', 'america', 'freedom']),
  e('🦉', 'Owl', 'animals', ['owl', 'wise', 'night', 'bird']),
  e('🦇', 'Bat', 'animals', ['bat', 'vampire', 'halloween', 'night']),
  e('🐺', 'Wolf', 'animals', ['wolf', 'howl', 'wild']),
  e('🐗', 'Boar', 'animals', ['boar', 'pig', 'wild']),
  e('🐴', 'Horse Face', 'animals', ['horse', 'pony', 'neigh']),
  e('🦄', 'Unicorn', 'animals', ['unicorn', 'magic', 'fantasy', 'rainbow']),
  e('🐝', 'Honeybee', 'animals', ['bee', 'honey', 'buzz', 'insect']),
  e('🪱', 'Worm', 'animals', ['worm', 'earth', 'crawl']),
  e('🐛', 'Bug', 'animals', ['bug', 'insect', 'caterpillar']),
  e('🦋', 'Butterfly', 'animals', ['butterfly', 'insect', 'beautiful', 'nature']),
  e('🐌', 'Snail', 'animals', ['snail', 'slow', 'shell']),
  e('🐞', 'Lady Beetle', 'animals', ['ladybug', 'insect', 'luck']),
  e('🐜', 'Ant', 'animals', ['ant', 'insect', 'small', 'colony']),
  e('🪰', 'Fly', 'animals', ['fly', 'insect', 'bug']),
  e('🪲', 'Beetle', 'animals', ['beetle', 'bug', 'insect']),
  e('🪳', 'Cockroach', 'animals', ['cockroach', 'bug', 'pest']),
  e('🦟', 'Mosquito', 'animals', ['mosquito', 'bite', 'insect']),
  e('🦗', 'Cricket', 'animals', ['cricket', 'insect', 'chirp']),
  e('🕷️', 'Spider', 'animals', ['spider', 'web', 'arachnid']),
  e('🕸️', 'Spider Web', 'animals', ['web', 'spider', 'cobweb']),
  e('🦂', 'Scorpion', 'animals', ['scorpion', 'sting', 'zodiac']),
  e('🐢', 'Turtle', 'animals', ['turtle', 'slow', 'shell', 'sea']),
  e('🐍', 'Snake', 'animals', ['snake', 'reptile', 'hiss']),
  e('🦎', 'Lizard', 'animals', ['lizard', 'reptile', 'gecko']),
  e('🦖', 'T-Rex', 'animals', ['dinosaur', 'trex', 'extinct', 'jurassic']),
  e('🦕', 'Sauropod', 'animals', ['dinosaur', 'brontosaurus', 'long neck']),
  e('🐙', 'Octopus', 'animals', ['octopus', 'sea', 'tentacles']),
  e('🦑', 'Squid', 'animals', ['squid', 'sea', 'ocean']),
  e('🦐', 'Shrimp', 'animals', ['shrimp', 'seafood', 'prawn']),
  e('🦞', 'Lobster', 'animals', ['lobster', 'seafood', 'claw']),
  e('🦀', 'Crab', 'animals', ['crab', 'seafood', 'beach']),
  e('🐡', 'Blowfish', 'animals', ['blowfish', 'puffer', 'fish']),
  e('🐠', 'Tropical Fish', 'animals', ['fish', 'tropical', 'nemo']),
  e('🐟', 'Fish', 'animals', ['fish', 'sea', 'swim']),
  e('🐬', 'Dolphin', 'animals', ['dolphin', 'sea', 'smart', 'flipper']),
  e('🐳', 'Spouting Whale', 'animals', ['whale', 'sea', 'ocean', 'spout']),
  e('🐋', 'Whale', 'animals', ['whale', 'sea', 'ocean', 'humpback']),
  e('🦈', 'Shark', 'animals', ['shark', 'fish', 'ocean', 'jaws']),
  e('🦭', 'Seal', 'animals', ['seal', 'sea lion', 'ocean']),
  e('🐊', 'Crocodile', 'animals', ['crocodile', 'alligator', 'reptile']),
  e('🐅', 'Tiger', 'animals', ['tiger', 'big cat', 'stripe']),
  e('🐆', 'Leopard', 'animals', ['leopard', 'big cat', 'spots']),
  e('🦓', 'Zebra', 'animals', ['zebra', 'stripes', 'africa']),
  e('🫏', 'Donkey', 'animals', ['donkey', 'mule', 'ass']),
  e('🦍', 'Gorilla', 'animals', ['gorilla', 'ape', 'primate', 'strong']),
  e('🦧', 'Orangutan', 'animals', ['orangutan', 'ape', 'primate']),
  e('🦣', 'Mammoth', 'animals', ['mammoth', 'extinct', 'woolly']),
  e('🐘', 'Elephant', 'animals', ['elephant', 'big', 'trunk', 'memory']),
  e('🦛', 'Hippopotamus', 'animals', ['hippo', 'water', 'africa']),
  e('🦏', 'Rhinoceros', 'animals', ['rhino', 'horn', 'africa']),
  e('🐪', 'Camel', 'animals', ['camel', 'desert', 'hump']),
  e('🐫', 'Two-Hump Camel', 'animals', ['camel', 'bactrian', 'desert']),
  e('🦒', 'Giraffe', 'animals', ['giraffe', 'tall', 'spots', 'africa']),
  e('🦘', 'Kangaroo', 'animals', ['kangaroo', 'australia', 'jump']),
  e('🦬', 'Bison', 'animals', ['bison', 'buffalo', 'wild west']),
  e('🐃', 'Water Buffalo', 'animals', ['buffalo', 'water', 'farm']),
  e('🐂', 'Ox', 'animals', ['ox', 'bull', 'strong']),
  e('🐄', 'Cow', 'animals', ['cow', 'farm', 'milk']),
  e('🐎', 'Horse', 'animals', ['horse', 'gallop', 'race']),
  e('🐖', 'Pig', 'animals', ['pig', 'pork', 'farm']),
  e('🐏', 'Ram', 'animals', ['ram', 'sheep', 'zodiac']),
  e('🐑', 'Ewe', 'animals', ['sheep', 'wool', 'lamb']),
  e('🦙', 'Llama', 'animals', ['llama', 'alpaca', 'wool']),
  e('🐐', 'Goat', 'animals', ['goat', 'farm', 'zodiac']),
  e('🦌', 'Deer', 'animals', ['deer', 'bambi', 'nature']),
  e('🐕', 'Dog', 'animals', ['dog', 'pet', 'faithful']),
  e('🐩', 'Poodle', 'animals', ['poodle', 'dog', 'fancy']),
  e('🦮', 'Guide Dog', 'animals', ['guide dog', 'accessibility', 'blind']),
  e('🐕‍🦺', 'Service Dog', 'animals', ['service dog', 'assistance', 'help']),
  e('🐈', 'Cat', 'animals', ['cat', 'pet', 'kitty']),
  e('🐈‍⬛', 'Black Cat', 'animals', ['black cat', 'halloween', 'superstition']),
  e('🪶', 'Feather', 'animals', ['feather', 'bird', 'quill', 'light']),
  e('🐓', 'Rooster', 'animals', ['rooster', 'chicken', 'farm', 'morning']),
  e('🦃', 'Turkey', 'animals', ['turkey', 'thanksgiving', 'bird']),
  e('🦤', 'Dodo', 'animals', ['dodo', 'extinct', 'bird']),
  e('🦚', 'Peacock', 'animals', ['peacock', 'bird', 'beautiful']),
  e('🦜', 'Parrot', 'animals', ['parrot', 'bird', 'pirate', 'talk']),
  e('🦢', 'Swan', 'animals', ['swan', 'bird', 'elegant', 'lake']),
  e('🦩', 'Flamingo', 'animals', ['flamingo', 'pink', 'bird']),
  e('🐇', 'Rabbit', 'animals', ['rabbit', 'bunny', 'fast']),
  e('🦔', 'Hedgehog', 'animals', ['hedgehog', 'spiny', 'sonic']),
  e('🦝', 'Raccoon', 'animals', ['raccoon', 'trash panda', 'sneaky']),
  e('🐿️', 'Chipmunk', 'animals', ['chipmunk', 'squirrel', 'nuts']),
  e('🦫', 'Beaver', 'animals', ['beaver', 'dam', 'wood']),
  e('🦦', 'Otter', 'animals', ['otter', 'cute', 'sea']),
  e('🦥', 'Sloth', 'animals', ['sloth', 'slow', 'lazy']),
  e('🐁', 'Mouse', 'animals', ['mouse', 'rodent', 'small']),
  e('🐀', 'Rat', 'animals', ['rat', 'rodent', 'zodiac']),
  e('🐾', 'Paw Prints', 'animals', ['paw', 'pet', 'animal', 'tracks']),
  e('🐉', 'Dragon', 'animals', ['dragon', 'fantasy', 'fire']),
  e('🐲', 'Dragon Face', 'animals', ['dragon', 'chinese', 'zodiac']),
  e('🌵', 'Cactus', 'animals', ['cactus', 'desert', 'plant']),
  e('🎄', 'Christmas Tree', 'animals', ['christmas', 'tree', 'holiday']),
  e('🌲', 'Evergreen Tree', 'animals', ['tree', 'pine', 'forest']),
  e('🌳', 'Deciduous Tree', 'animals', ['tree', 'nature', 'forest']),
  e('🌴', 'Palm Tree', 'animals', ['palm', 'tropical', 'beach', 'island']),
  e('🪵', 'Wood', 'animals', ['wood', 'log', 'lumber', 'tree']),
  e('🌱', 'Seedling', 'animals', ['seedling', 'plant', 'grow', 'sprout']),
  e('🌿', 'Herb', 'animals', ['herb', 'plant', 'leaf', 'green']),
  e('☘️', 'Shamrock', 'animals', ['shamrock', 'clover', 'irish']),
  e('🍀', 'Four Leaf Clover', 'animals', ['luck', 'clover', 'irish', 'lucky']),
  e('🎍', 'Pine Decoration', 'animals', ['bamboo', 'japanese', 'new year']),
  e('🪴', 'Potted Plant', 'animals', ['plant', 'pot', 'indoor', 'houseplant']),
  e('🎋', 'Tanabata Tree', 'animals', ['tanabata', 'japanese', 'wish']),
  e('🍃', 'Leaf Fluttering in Wind', 'animals', ['leaf', 'wind', 'nature']),
  e('🍂', 'Fallen Leaf', 'animals', ['leaf', 'autumn', 'fall']),
  e('🍁', 'Maple Leaf', 'animals', ['maple', 'canada', 'autumn', 'fall']),
  e('🌾', 'Sheaf of Rice', 'animals', ['rice', 'grain', 'wheat', 'harvest']),
  e('🪻', 'Hyacinth', 'animals', ['hyacinth', 'flower', 'spring']),
  e('🌺', 'Hibiscus', 'animals', ['hibiscus', 'flower', 'tropical']),
  e('🌻', 'Sunflower', 'animals', ['sunflower', 'flower', 'yellow', 'sun']),
  e('🌹', 'Rose', 'animals', ['rose', 'flower', 'love', 'red']),
  e('🥀', 'Wilted Flower', 'animals', ['wilted', 'dead', 'flower', 'sad']),
  e('🌷', 'Tulip', 'animals', ['tulip', 'flower', 'spring', 'dutch']),
  e('🌼', 'Blossom', 'animals', ['blossom', 'flower', 'spring']),
  e('🌸', 'Cherry Blossom', 'animals', ['cherry blossom', 'sakura', 'spring', 'japan']),
  e('💐', 'Bouquet', 'animals', ['bouquet', 'flowers', 'gift']),
  e('🍄', 'Mushroom', 'animals', ['mushroom', 'fungus', 'toadstool']),
  e('🪨', 'Rock', 'animals', ['rock', 'stone', 'boulder']),
  e('🪸', 'Coral', 'animals', ['coral', 'ocean', 'reef']),
  e('🌍', 'Globe Showing Europe-Africa', 'animals', ['earth', 'world', 'globe', 'europe', 'africa']),
  e('🌎', 'Globe Showing Americas', 'animals', ['earth', 'world', 'globe', 'americas']),
  e('🌏', 'Globe Showing Asia-Australia', 'animals', ['earth', 'world', 'globe', 'asia']),
  e('🌕', 'Full Moon', 'animals', ['moon', 'full', 'night']),
  e('🌙', 'Crescent Moon', 'animals', ['moon', 'crescent', 'night', 'sleep']),
  e('⭐', 'Star', 'animals', ['star', 'favorite', 'night']),
  e('🌟', 'Glowing Star', 'animals', ['star', 'sparkle', 'shine', 'glow']),
  e('✨', 'Sparkles', 'animals', ['sparkle', 'shine', 'magic', 'clean', 'new']),
  e('⚡', 'High Voltage', 'animals', ['lightning', 'electric', 'power', 'fast', 'thunder']),
  e('🔥', 'Fire', 'animals', ['fire', 'hot', 'flame', 'lit', 'trending']),
  e('🌈', 'Rainbow', 'animals', ['rainbow', 'colors', 'pride', 'weather']),
  e('☀️', 'Sun', 'animals', ['sun', 'sunny', 'hot', 'weather']),
  e('🌤️', 'Sun Behind Small Cloud', 'animals', ['sun', 'cloud', 'weather']),
  e('⛅', 'Sun Behind Cloud', 'animals', ['cloud', 'sun', 'weather']),
  e('🌧️', 'Cloud with Rain', 'animals', ['rain', 'cloud', 'weather']),
  e('⛈️', 'Cloud with Lightning and Rain', 'animals', ['storm', 'thunder', 'weather']),
  e('🌩️', 'Cloud with Lightning', 'animals', ['lightning', 'storm', 'weather']),
  e('❄️', 'Snowflake', 'animals', ['snow', 'winter', 'cold', 'ice']),
  e('☃️', 'Snowman', 'animals', ['snowman', 'winter', 'snow']),
  e('🌊', 'Water Wave', 'animals', ['wave', 'ocean', 'sea', 'water', 'surf']),
  e('🌫️', 'Fog', 'animals', ['fog', 'mist', 'hazy']),
  e('💧', 'Droplet', 'animals', ['water', 'drop', 'rain', 'tear']),
  e('☔', 'Umbrella with Rain Drops', 'animals', ['rain', 'umbrella', 'weather']),

  // ===== FOOD & DRINK =====
  e('🍎', 'Red Apple', 'food', ['apple', 'fruit', 'red', 'healthy']),
  e('🍏', 'Green Apple', 'food', ['apple', 'fruit', 'green']),
  e('🍐', 'Pear', 'food', ['pear', 'fruit']),
  e('🍊', 'Tangerine', 'food', ['orange', 'tangerine', 'citrus', 'fruit']),
  e('🍋', 'Lemon', 'food', ['lemon', 'citrus', 'sour']),
  e('🍌', 'Banana', 'food', ['banana', 'fruit', 'yellow']),
  e('🍉', 'Watermelon', 'food', ['watermelon', 'fruit', 'summer']),
  e('🍇', 'Grapes', 'food', ['grapes', 'fruit', 'wine', 'purple']),
  e('🍓', 'Strawberry', 'food', ['strawberry', 'fruit', 'berry', 'red']),
  e('🫐', 'Blueberries', 'food', ['blueberry', 'berry', 'fruit']),
  e('🍈', 'Melon', 'food', ['melon', 'fruit', 'cantaloupe']),
  e('🍒', 'Cherries', 'food', ['cherry', 'fruit', 'red']),
  e('🍑', 'Peach', 'food', ['peach', 'fruit', 'butt']),
  e('🥭', 'Mango', 'food', ['mango', 'fruit', 'tropical']),
  e('🍍', 'Pineapple', 'food', ['pineapple', 'fruit', 'tropical']),
  e('🥥', 'Coconut', 'food', ['coconut', 'tropical', 'palm']),
  e('🥝', 'Kiwi Fruit', 'food', ['kiwi', 'fruit', 'green']),
  e('🍅', 'Tomato', 'food', ['tomato', 'vegetable', 'red']),
  e('🫒', 'Olive', 'food', ['olive', 'oil', 'mediterranean']),
  e('🥑', 'Avocado', 'food', ['avocado', 'guacamole', 'healthy', 'toast']),
  e('🍆', 'Eggplant', 'food', ['eggplant', 'aubergine', 'vegetable']),
  e('🥔', 'Potato', 'food', ['potato', 'vegetable', 'spud', 'fries']),
  e('🥕', 'Carrot', 'food', ['carrot', 'vegetable', 'orange']),
  e('🌽', 'Ear of Corn', 'food', ['corn', 'vegetable', 'maize']),
  e('🌶️', 'Hot Pepper', 'food', ['pepper', 'hot', 'spicy', 'chili']),
  e('🫑', 'Bell Pepper', 'food', ['pepper', 'vegetable', 'capsicum']),
  e('🥒', 'Cucumber', 'food', ['cucumber', 'vegetable', 'pickle']),
  e('🥬', 'Leafy Green', 'food', ['lettuce', 'salad', 'vegetable', 'kale']),
  e('🥦', 'Broccoli', 'food', ['broccoli', 'vegetable', 'green']),
  e('🧄', 'Garlic', 'food', ['garlic', 'cooking', 'vampire']),
  e('🧅', 'Onion', 'food', ['onion', 'cooking', 'cry']),
  e('🥜', 'Peanuts', 'food', ['peanut', 'nut', 'snack']),
  e('🫘', 'Beans', 'food', ['beans', 'legume', 'kidney']),
  e('🌰', 'Chestnut', 'food', ['chestnut', 'nut', 'autumn']),
  e('🫚', 'Ginger', 'food', ['ginger', 'spice', 'root']),
  e('🍞', 'Bread', 'food', ['bread', 'loaf', 'bake', 'toast']),
  e('🥐', 'Croissant', 'food', ['croissant', 'french', 'pastry', 'bread']),
  e('🥖', 'Baguette Bread', 'food', ['baguette', 'french', 'bread']),
  e('🫓', 'Flatbread', 'food', ['flatbread', 'naan', 'pita']),
  e('🥨', 'Pretzel', 'food', ['pretzel', 'snack', 'german']),
  e('🥯', 'Bagel', 'food', ['bagel', 'bread', 'breakfast']),
  e('🥞', 'Pancakes', 'food', ['pancake', 'breakfast', 'maple']),
  e('🧇', 'Waffle', 'food', ['waffle', 'breakfast']),
  e('🧀', 'Cheese Wedge', 'food', ['cheese', 'dairy', 'cheddar']),
  e('🍖', 'Meat on Bone', 'food', ['meat', 'bone', 'bbq']),
  e('🍗', 'Poultry Leg', 'food', ['chicken', 'drumstick', 'turkey', 'leg']),
  e('🥩', 'Cut of Meat', 'food', ['steak', 'meat', 'beef']),
  e('🥓', 'Bacon', 'food', ['bacon', 'meat', 'breakfast']),
  e('🍔', 'Hamburger', 'food', ['burger', 'hamburger', 'fast food', 'beef']),
  e('🍟', 'French Fries', 'food', ['fries', 'fast food', 'potato']),
  e('🍕', 'Pizza', 'food', ['pizza', 'italian', 'slice', 'cheese']),
  e('🌭', 'Hot Dog', 'food', ['hot dog', 'sausage', 'fast food']),
  e('🥪', 'Sandwich', 'food', ['sandwich', 'bread', 'lunch']),
  e('🌮', 'Taco', 'food', ['taco', 'mexican', 'tuesday']),
  e('🌯', 'Burrito', 'food', ['burrito', 'mexican', 'wrap']),
  e('🫔', 'Tamale', 'food', ['tamale', 'mexican', 'corn']),
  e('🥙', 'Stuffed Flatbread', 'food', ['pita', 'falafel', 'kebab']),
  e('🧆', 'Falafel', 'food', ['falafel', 'middle eastern']),
  e('🥚', 'Egg', 'food', ['egg', 'breakfast', 'chicken']),
  e('🍳', 'Cooking', 'food', ['egg', 'frying', 'pan', 'breakfast']),
  e('🥘', 'Shallow Pan of Food', 'food', ['paella', 'curry', 'pan', 'cooking']),
  e('🍲', 'Pot of Food', 'food', ['stew', 'pot', 'soup', 'cooking']),
  e('🫕', 'Fondue', 'food', ['fondue', 'cheese', 'swiss']),
  e('🥣', 'Bowl with Spoon', 'food', ['cereal', 'bowl', 'soup', 'breakfast']),
  e('🥗', 'Green Salad', 'food', ['salad', 'healthy', 'vegetable']),
  e('🍿', 'Popcorn', 'food', ['popcorn', 'movie', 'snack']),
  e('🧈', 'Butter', 'food', ['butter', 'dairy', 'toast']),
  e('🧂', 'Salt', 'food', ['salt', 'seasoning', 'salty']),
  e('🥫', 'Canned Food', 'food', ['can', 'canned', 'preserved']),
  e('🍱', 'Bento Box', 'food', ['bento', 'japanese', 'lunch box']),
  e('🍘', 'Rice Cracker', 'food', ['rice cracker', 'japanese', 'snack']),
  e('🍙', 'Rice Ball', 'food', ['onigiri', 'rice ball', 'japanese']),
  e('🍚', 'Cooked Rice', 'food', ['rice', 'bowl', 'asian']),
  e('🍛', 'Curry Rice', 'food', ['curry', 'rice', 'japanese', 'indian']),
  e('🍜', 'Steaming Bowl', 'food', ['ramen', 'noodle', 'soup', 'pho']),
  e('🍝', 'Spaghetti', 'food', ['spaghetti', 'pasta', 'italian', 'noodle']),
  e('🍠', 'Roasted Sweet Potato', 'food', ['sweet potato', 'yam', 'roasted']),
  e('🍢', 'Oden', 'food', ['oden', 'japanese', 'skewer']),
  e('🍣', 'Sushi', 'food', ['sushi', 'japanese', 'fish', 'rice']),
  e('🍤', 'Fried Shrimp', 'food', ['shrimp', 'tempura', 'fried']),
  e('🍥', 'Fish Cake with Swirl', 'food', ['narutomaki', 'fish cake', 'japanese']),
  e('🥮', 'Moon Cake', 'food', ['mooncake', 'chinese', 'autumn']),
  e('🍡', 'Dango', 'food', ['dango', 'japanese', 'dessert']),
  e('🥟', 'Dumpling', 'food', ['dumpling', 'gyoza', 'chinese', 'dim sum']),
  e('🥠', 'Fortune Cookie', 'food', ['fortune cookie', 'chinese', 'luck']),
  e('🥡', 'Takeout Box', 'food', ['takeout', 'chinese', 'food box']),
  e('🦀', 'Crab', 'food', ['crab', 'seafood', 'zodiac']),
  e('🍦', 'Soft Ice Cream', 'food', ['ice cream', 'dessert', 'cone', 'soft serve']),
  e('🍧', 'Shaved Ice', 'food', ['shaved ice', 'dessert', 'snow cone']),
  e('🍨', 'Ice Cream', 'food', ['ice cream', 'dessert', 'scoop']),
  e('🍩', 'Doughnut', 'food', ['donut', 'doughnut', 'dessert', 'sweet']),
  e('🍪', 'Cookie', 'food', ['cookie', 'dessert', 'sweet', 'biscuit']),
  e('🎂', 'Birthday Cake', 'food', ['cake', 'birthday', 'celebration', 'candle']),
  e('🍰', 'Shortcake', 'food', ['cake', 'dessert', 'strawberry']),
  e('🧁', 'Cupcake', 'food', ['cupcake', 'dessert', 'sweet', 'muffin']),
  e('🥧', 'Pie', 'food', ['pie', 'dessert', 'bake']),
  e('🍫', 'Chocolate Bar', 'food', ['chocolate', 'candy', 'sweet']),
  e('🍬', 'Candy', 'food', ['candy', 'sweet', 'sugar']),
  e('🍭', 'Lollipop', 'food', ['lollipop', 'candy', 'sweet']),
  e('🍮', 'Custard', 'food', ['custard', 'pudding', 'dessert', 'flan']),
  e('🍯', 'Honey Pot', 'food', ['honey', 'sweet', 'bee']),
  e('🍼', 'Baby Bottle', 'food', ['baby', 'bottle', 'milk']),
  e('🥛', 'Glass of Milk', 'food', ['milk', 'glass', 'dairy']),
  e('☕', 'Hot Beverage', 'food', ['coffee', 'tea', 'hot', 'drink', 'cafe']),
  e('🫖', 'Teapot', 'food', ['tea', 'teapot', 'pot']),
  e('🍵', 'Teacup Without Handle', 'food', ['tea', 'green tea', 'japanese']),
  e('🍶', 'Sake', 'food', ['sake', 'japanese', 'alcohol', 'rice wine']),
  e('🍾', 'Bottle with Popping Cork', 'food', ['champagne', 'celebration', 'party']),
  e('🍷', 'Wine Glass', 'food', ['wine', 'glass', 'alcohol', 'red']),
  e('🍸', 'Cocktail Glass', 'food', ['cocktail', 'martini', 'drink', 'bar']),
  e('🍹', 'Tropical Drink', 'food', ['tropical', 'cocktail', 'drink', 'vacation']),
  e('🍺', 'Beer Mug', 'food', ['beer', 'drink', 'bar', 'pub']),
  e('🍻', 'Clinking Beer Mugs', 'food', ['beer', 'cheers', 'toast', 'drink']),
  e('🥂', 'Clinking Glasses', 'food', ['champagne', 'cheers', 'toast', 'celebration']),
  e('🥃', 'Tumbler Glass', 'food', ['whiskey', 'bourbon', 'drink', 'glass']),
  e('🫗', 'Pouring Liquid', 'food', ['pour', 'liquid', 'water', 'drink']),
  e('🥤', 'Cup with Straw', 'food', ['soda', 'drink', 'straw', 'cup']),
  e('🧋', 'Bubble Tea', 'food', ['bubble tea', 'boba', 'milk tea', 'drink']),
  e('🧃', 'Beverage Box', 'food', ['juice box', 'drink', 'kid']),
  e('🧉', 'Mate', 'food', ['mate', 'tea', 'argentina']),
  e('🧊', 'Ice', 'food', ['ice', 'cube', 'cold', 'frozen']),
  e('🥄', 'Spoon', 'food', ['spoon', 'utensil', 'eat']),
  e('🍽️', 'Fork and Knife with Plate', 'food', ['plate', 'dinner', 'restaurant', 'eat']),
  e('🥢', 'Chopsticks', 'food', ['chopsticks', 'asian', 'eat']),

  // ===== TRAVEL & PLACES =====
  e('🚗', 'Automobile', 'travel', ['car', 'drive', 'vehicle', 'red']),
  e('🚕', 'Taxi', 'travel', ['taxi', 'cab', 'uber']),
  e('🚙', 'Sport Utility Vehicle', 'travel', ['suv', 'car', 'vehicle']),
  e('🚌', 'Bus', 'travel', ['bus', 'transit', 'public']),
  e('🚎', 'Trolleybus', 'travel', ['trolleybus', 'transit']),
  e('🏎️', 'Racing Car', 'travel', ['racing', 'fast', 'car', 'f1']),
  e('🚓', 'Police Car', 'travel', ['police', 'car', 'cop']),
  e('🚑', 'Ambulance', 'travel', ['ambulance', 'emergency', 'hospital']),
  e('🚒', 'Fire Engine', 'travel', ['fire', 'truck', 'emergency']),
  e('🚐', 'Minibus', 'travel', ['van', 'minibus', 'shuttle']),
  e('🛻', 'Pickup Truck', 'travel', ['truck', 'pickup', 'vehicle']),
  e('🚚', 'Delivery Truck', 'travel', ['truck', 'delivery', 'shipping']),
  e('🚛', 'Articulated Lorry', 'travel', ['truck', 'semi', 'lorry']),
  e('🚜', 'Tractor', 'travel', ['tractor', 'farm', 'vehicle']),
  e('🏍️', 'Motorcycle', 'travel', ['motorcycle', 'bike', 'ride']),
  e('🛵', 'Motor Scooter', 'travel', ['scooter', 'vespa', 'moped']),
  e('🚲', 'Bicycle', 'travel', ['bike', 'bicycle', 'cycle', 'ride']),
  e('🛴', 'Kick Scooter', 'travel', ['scooter', 'kick', 'ride']),
  e('🚆', 'Train', 'travel', ['train', 'rail', 'transit']),
  e('🚇', 'Metro', 'travel', ['metro', 'subway', 'underground']),
  e('🚈', 'Light Rail', 'travel', ['light rail', 'tram', 'transit']),
  e('🚂', 'Locomotive', 'travel', ['train', 'steam', 'locomotive']),
  e('🚀', 'Rocket', 'travel', ['rocket', 'space', 'launch', 'fast']),
  e('🛸', 'Flying Saucer', 'travel', ['ufo', 'alien', 'space']),
  e('🛩️', 'Small Airplane', 'travel', ['airplane', 'small', 'plane']),
  e('✈️', 'Airplane', 'travel', ['airplane', 'flight', 'travel', 'plane']),
  e('🚁', 'Helicopter', 'travel', ['helicopter', 'fly', 'chopper']),
  e('🛶', 'Canoe', 'travel', ['canoe', 'kayak', 'paddle']),
  e('⛵', 'Sailboat', 'travel', ['sailboat', 'boat', 'sail', 'sea']),
  e('🚤', 'Speedboat', 'travel', ['speedboat', 'fast', 'boat']),
  e('🛳️', 'Passenger Ship', 'travel', ['cruise', 'ship', 'boat']),
  e('⛴️', 'Ferry', 'travel', ['ferry', 'boat', 'ship']),
  e('🚢', 'Ship', 'travel', ['ship', 'boat', 'cruise']),
  e('⚓', 'Anchor', 'travel', ['anchor', 'ship', 'sea', 'port']),
  e('⛽', 'Fuel Pump', 'travel', ['gas', 'fuel', 'station', 'petrol']),
  e('🚧', 'Construction', 'travel', ['construction', 'barrier', 'wip']),
  e('🚦', 'Vertical Traffic Light', 'travel', ['traffic light', 'signal']),
  e('🚥', 'Horizontal Traffic Light', 'travel', ['traffic light', 'signal']),
  e('🗺️', 'World Map', 'travel', ['map', 'world', 'travel']),
  e('🗿', 'Moai', 'travel', ['moai', 'easter island', 'stone', 'statue']),
  e('🗽', 'Statue of Liberty', 'travel', ['statue of liberty', 'new york', 'usa', 'freedom']),
  e('🗼', 'Tokyo Tower', 'travel', ['tokyo', 'tower', 'japan']),
  e('🏰', 'Castle', 'travel', ['castle', 'european', 'medieval']),
  e('🏯', 'Japanese Castle', 'travel', ['castle', 'japanese']),
  e('🏟️', 'Stadium', 'travel', ['stadium', 'arena', 'sports']),
  e('🎡', 'Ferris Wheel', 'travel', ['ferris wheel', 'amusement park', 'ride']),
  e('🎢', 'Roller Coaster', 'travel', ['roller coaster', 'amusement park', 'ride']),
  e('🎠', 'Carousel Horse', 'travel', ['carousel', 'horse', 'ride']),
  e('⛲', 'Fountain', 'travel', ['fountain', 'water', 'park']),
  e('⛱️', 'Umbrella on Ground', 'travel', ['beach', 'umbrella', 'sun']),
  e('🏖️', 'Beach with Umbrella', 'travel', ['beach', 'vacation', 'sand', 'sun']),
  e('🏝️', 'Desert Island', 'travel', ['island', 'desert', 'tropical']),
  e('🏜️', 'Desert', 'travel', ['desert', 'sand', 'dry']),
  e('🌋', 'Volcano', 'travel', ['volcano', 'eruption', 'lava']),
  e('⛰️', 'Mountain', 'travel', ['mountain', 'nature', 'hike']),
  e('🏔️', 'Snow-Capped Mountain', 'travel', ['mountain', 'snow', 'cold']),
  e('🗻', 'Mount Fuji', 'travel', ['fuji', 'mountain', 'japan']),
  e('🏕️', 'Camping', 'travel', ['camping', 'tent', 'outdoor']),
  e('🏠', 'House', 'travel', ['house', 'home', 'building']),
  e('🏡', 'House with Garden', 'travel', ['house', 'garden', 'home']),
  e('🏢', 'Office Building', 'travel', ['office', 'building', 'work']),
  e('🏣', 'Japanese Post Office', 'travel', ['post office', 'japanese']),
  e('🏥', 'Hospital', 'travel', ['hospital', 'medical', 'health']),
  e('🏦', 'Bank', 'travel', ['bank', 'money', 'finance']),
  e('🏨', 'Hotel', 'travel', ['hotel', 'travel', 'lodging']),
  e('🏪', 'Convenience Store', 'travel', ['convenience store', 'shop', '24/7']),
  e('🏫', 'School', 'travel', ['school', 'education', 'study']),
  e('🏬', 'Department Store', 'travel', ['department store', 'shopping', 'mall']),
  e('🏭', 'Factory', 'travel', ['factory', 'industry', 'manufacture']),
  e('🏗️', 'Building Construction', 'travel', ['construction', 'building', 'crane']),
  e('⛪', 'Church', 'travel', ['church', 'religion', 'christian']),
  e('🕌', 'Mosque', 'travel', ['mosque', 'islam', 'muslim']),
  e('🛕', 'Hindu Temple', 'travel', ['temple', 'hindu', 'india']),
  e('🕍', 'Synagogue', 'travel', ['synagogue', 'jewish', 'temple']),
  e('⛩️', 'Shinto Shrine', 'travel', ['shrine', 'shinto', 'japan']),
  e('🕋', 'Kaaba', 'travel', ['kaaba', 'mecca', 'islam']),
  e('🌃', 'Night with Stars', 'travel', ['night', 'stars', 'city']),
  e('🌆', 'Cityscape at Dusk', 'travel', ['city', 'dusk', 'sunset']),
  e('🌇', 'Sunset', 'travel', ['sunset', 'city', 'evening']),
  e('🌉', 'Bridge at Night', 'travel', ['bridge', 'night', 'city']),
  e('🎆', 'Fireworks', 'travel', ['fireworks', 'celebration', 'new year']),
  e('🎇', 'Sparkler', 'travel', ['sparkler', 'celebration', 'firework']),
  e('🌌', 'Milky Way', 'travel', ['milky way', 'galaxy', 'space', 'stars']),
  e('🎑', 'Moon Viewing Ceremony', 'travel', ['moon', 'ceremony', 'japanese']),

  // ===== ACTIVITIES =====
  e('⚽', 'Soccer Ball', 'activities', ['soccer', 'football', 'ball', 'sport']),
  e('🏀', 'Basketball', 'activities', ['basketball', 'ball', 'sport', 'nba']),
  e('🏈', 'American Football', 'activities', ['football', 'american', 'nfl', 'sport']),
  e('⚾', 'Baseball', 'activities', ['baseball', 'ball', 'sport', 'mlb']),
  e('🥎', 'Softball', 'activities', ['softball', 'ball', 'sport']),
  e('🎾', 'Tennis', 'activities', ['tennis', 'ball', 'racket', 'sport']),
  e('🏐', 'Volleyball', 'activities', ['volleyball', 'ball', 'sport']),
  e('🏉', 'Rugby Football', 'activities', ['rugby', 'ball', 'sport']),
  e('🥏', 'Flying Disc', 'activities', ['frisbee', 'disc', 'sport']),
  e('🎱', 'Pool 8 Ball', 'activities', ['pool', 'billiards', '8 ball']),
  e('🪀', 'Yo-Yo', 'activities', ['yoyo', 'toy', 'play']),
  e('🏓', 'Ping Pong', 'activities', ['ping pong', 'table tennis', 'sport']),
  e('🏸', 'Badminton', 'activities', ['badminton', 'sport', 'racket']),
  e('🏒', 'Ice Hockey', 'activities', ['hockey', 'ice', 'sport', 'nhl']),
  e('🏑', 'Field Hockey', 'activities', ['hockey', 'field', 'sport']),
  e('🥍', 'Lacrosse', 'activities', ['lacrosse', 'sport']),
  e('🏏', 'Cricket Game', 'activities', ['cricket', 'sport', 'bat']),
  e('🪃', 'Boomerang', 'activities', ['boomerang', 'throw', 'australia']),
  e('🥅', 'Goal Net', 'activities', ['goal', 'net', 'sport']),
  e('⛳', 'Flag in Hole', 'activities', ['golf', 'flag', 'sport']),
  e('🪁', 'Kite', 'activities', ['kite', 'fly', 'wind']),
  e('🏹', 'Bow and Arrow', 'activities', ['archery', 'bow', 'arrow']),
  e('🎣', 'Fishing Pole', 'activities', ['fishing', 'pole', 'fish']),
  e('🤿', 'Diving Mask', 'activities', ['diving', 'snorkel', 'swim']),
  e('🥊', 'Boxing Glove', 'activities', ['boxing', 'fight', 'punch']),
  e('🥋', 'Martial Arts Uniform', 'activities', ['martial arts', 'karate', 'judo']),
  e('🎽', 'Running Shirt', 'activities', ['running', 'shirt', 'sport']),
  e('⛸️', 'Ice Skate', 'activities', ['ice skating', 'skate', 'winter']),
  e('🥌', 'Curling Stone', 'activities', ['curling', 'sport', 'winter']),
  e('🛷', 'Sled', 'activities', ['sled', 'toboggan', 'winter']),
  e('🎿', 'Skis', 'activities', ['ski', 'winter', 'snow', 'sport']),
  e('⛷️', 'Skier', 'activities', ['ski', 'winter', 'snow']),
  e('🏂', 'Snowboarder', 'activities', ['snowboard', 'winter', 'sport']),
  e('🪂', 'Parachute', 'activities', ['parachute', 'skydive', 'fly']),
  e('🏋️', 'Person Lifting Weights', 'activities', ['gym', 'weightlifting', 'exercise', 'strong']),
  e('🤸', 'Person Cartwheeling', 'activities', ['cartwheel', 'gymnastics', 'acrobat']),
  e('🤼', 'People Wrestling', 'activities', ['wrestling', 'fight', 'sport']),
  e('🤺', 'Person Fencing', 'activities', ['fencing', 'sword', 'sport']),
  e('🤾', 'Person Playing Handball', 'activities', ['handball', 'sport']),
  e('🏌️', 'Person Golfing', 'activities', ['golf', 'sport']),
  e('🏇', 'Horse Racing', 'activities', ['horse racing', 'jockey', 'sport']),
  e('🧘', 'Person in Lotus Position', 'activities', ['yoga', 'meditation', 'zen', 'calm']),
  e('🏄', 'Person Surfing', 'activities', ['surf', 'wave', 'ocean', 'sport']),
  e('🏊', 'Person Swimming', 'activities', ['swim', 'pool', 'sport']),
  e('🤽', 'Person Playing Water Polo', 'activities', ['water polo', 'sport']),
  e('🚣', 'Person Rowing Boat', 'activities', ['rowing', 'boat', 'sport']),
  e('🧗', 'Person Climbing', 'activities', ['climbing', 'rock', 'sport']),
  e('🚵', 'Person Mountain Biking', 'activities', ['mountain biking', 'bike', 'sport']),
  e('🚴', 'Person Biking', 'activities', ['biking', 'cycling', 'bike', 'sport']),
  e('🏆', 'Trophy', 'activities', ['trophy', 'winner', 'award', 'champion']),
  e('🥇', 'Gold Medal', 'activities', ['gold', 'medal', 'first', 'winner']),
  e('🥈', 'Silver Medal', 'activities', ['silver', 'medal', 'second']),
  e('🥉', 'Bronze Medal', 'activities', ['bronze', 'medal', 'third']),
  e('🏅', 'Sports Medal', 'activities', ['medal', 'sports', 'achievement']),
  e('🎖️', 'Military Medal', 'activities', ['medal', 'military', 'honor']),
  e('🏵️', 'Rosette', 'activities', ['rosette', 'flower', 'award']),
  e('🎗️', 'Reminder Ribbon', 'activities', ['ribbon', 'awareness', 'support']),
  e('🎫', 'Ticket', 'activities', ['ticket', 'event', 'admission']),
  e('🎟️', 'Admission Tickets', 'activities', ['tickets', 'event', 'movie']),
  e('🎪', 'Circus Tent', 'activities', ['circus', 'tent', 'show']),
  e('🤹', 'Person Juggling', 'activities', ['juggle', 'circus', 'skill']),
  e('🎭', 'Performing Arts', 'activities', ['theater', 'drama', 'mask', 'comedy', 'tragedy']),
  e('🩰', 'Ballet Shoes', 'activities', ['ballet', 'dance', 'shoes']),
  e('🎨', 'Artist Palette', 'activities', ['art', 'paint', 'palette', 'creative']),
  e('🎬', 'Clapper Board', 'activities', ['movie', 'film', 'action', 'cinema']),
  e('🎤', 'Microphone', 'activities', ['microphone', 'sing', 'karaoke', 'music']),
  e('🎧', 'Headphone', 'activities', ['headphones', 'music', 'listen', 'audio']),
  e('🎼', 'Musical Score', 'activities', ['music', 'score', 'notes']),
  e('🎹', 'Musical Keyboard', 'activities', ['piano', 'keyboard', 'music']),
  e('🥁', 'Drum', 'activities', ['drum', 'music', 'beat']),
  e('🪘', 'Long Drum', 'activities', ['drum', 'african', 'music']),
  e('🎷', 'Saxophone', 'activities', ['sax', 'saxophone', 'music', 'jazz']),
  e('🎺', 'Trumpet', 'activities', ['trumpet', 'music', 'brass']),
  e('🪗', 'Accordion', 'activities', ['accordion', 'music']),
  e('🎸', 'Guitar', 'activities', ['guitar', 'music', 'rock']),
  e('🪕', 'Banjo', 'activities', ['banjo', 'music', 'country']),
  e('🎻', 'Violin', 'activities', ['violin', 'music', 'classical']),
  e('🎲', 'Game Die', 'activities', ['dice', 'game', 'random', 'luck']),
  e('♟️', 'Chess Pawn', 'activities', ['chess', 'game', 'strategy']),
  e('🎯', 'Bullseye', 'activities', ['target', 'bullseye', 'dart', 'goal']),
  e('🎳', 'Bowling', 'activities', ['bowling', 'sport', 'pins']),
  e('🎮', 'Video Game', 'activities', ['game', 'controller', 'gaming', 'play']),
  e('🕹️', 'Joystick', 'activities', ['joystick', 'game', 'arcade']),
  e('🎰', 'Slot Machine', 'activities', ['slot', 'casino', 'gambling']),
  e('🧩', 'Puzzle Piece', 'activities', ['puzzle', 'jigsaw', 'piece']),
  e('🪄', 'Magic Wand', 'activities', ['magic', 'wand', 'wizard', 'spell']),
  e('🎃', 'Jack-O-Lantern', 'activities', ['halloween', 'pumpkin', 'scary']),
  e('🎄', 'Christmas Tree', 'activities', ['christmas', 'tree', 'holiday']),
  e('🎆', 'Fireworks', 'activities', ['fireworks', 'celebration', 'new year']),
  e('🎈', 'Balloon', 'activities', ['balloon', 'party', 'birthday']),
  e('🎉', 'Party Popper', 'activities', ['party', 'celebration', 'confetti', 'tada']),
  e('🎊', 'Confetti Ball', 'activities', ['confetti', 'party', 'celebration']),
  e('🎋', 'Tanabata Tree', 'activities', ['tanabata', 'japanese', 'wish']),
  e('🎍', 'Pine Decoration', 'activities', ['bamboo', 'japanese', 'new year']),
  e('🎎', 'Japanese Dolls', 'activities', ['dolls', 'japanese', 'hinamatsuri']),
  e('🎏', 'Carp Streamer', 'activities', ['carp streamer', 'japanese', 'boys day']),
  e('🎐', 'Wind Chime', 'activities', ['wind chime', 'japanese', 'bell']),
  e('🎑', 'Moon Viewing Ceremony', 'activities', ['moon', 'ceremony', 'japanese']),
  e('🧧', 'Red Envelope', 'activities', ['red envelope', 'chinese', 'lucky money']),
  e('🎀', 'Ribbon', 'activities', ['ribbon', 'bow', 'gift', 'pink']),
  e('🎁', 'Wrapped Gift', 'activities', ['gift', 'present', 'birthday', 'christmas']),
  e('🎗️', 'Reminder Ribbon', 'activities', ['ribbon', 'awareness']),
  e('🎮', 'Video Game', 'activities', ['game', 'controller', 'play']),

  // ===== OBJECTS =====
  e('⌚', 'Watch', 'objects', ['watch', 'time', 'clock']),
  e('📱', 'Mobile Phone', 'objects', ['phone', 'mobile', 'cell', 'iphone']),
  e('📲', 'Mobile Phone with Arrow', 'objects', ['phone', 'call', 'incoming']),
  e('💻', 'Laptop', 'objects', ['laptop', 'computer', 'pc', 'work']),
  e('⌨️', 'Keyboard', 'objects', ['keyboard', 'type', 'computer']),
  e('🖥️', 'Desktop Computer', 'objects', ['computer', 'desktop', 'monitor']),
  e('🖨️', 'Printer', 'objects', ['printer', 'print', 'paper']),
  e('🖱️', 'Computer Mouse', 'objects', ['mouse', 'computer', 'click']),
  e('🖲️', 'Trackball', 'objects', ['trackball', 'computer', 'input']),
  e('🕹️', 'Joystick', 'objects', ['joystick', 'game', 'arcade']),
  e('💾', 'Floppy Disk', 'objects', ['floppy', 'save', 'disk', 'retro']),
  e('💿', 'Optical Disk', 'objects', ['cd', 'disk', 'dvd']),
  e('📀', 'DVD', 'objects', ['dvd', 'disk', 'movie']),
  e('📼', 'Videocassette', 'objects', ['vhs', 'tape', 'video', 'retro']),
  e('📷', 'Camera', 'objects', ['camera', 'photo', 'picture']),
  e('📸', 'Camera with Flash', 'objects', ['camera', 'flash', 'photo']),
  e('📹', 'Video Camera', 'objects', ['video', 'camera', 'record']),
  e('🎥', 'Movie Camera', 'objects', ['movie', 'film', 'camera']),
  e('📽️', 'Film Projector', 'objects', ['projector', 'film', 'movie']),
  e('📺', 'Television', 'objects', ['tv', 'television', 'watch', 'screen']),
  e('📻', 'Radio', 'objects', ['radio', 'music', 'broadcast']),
  e('🎙️', 'Studio Microphone', 'objects', ['microphone', 'podcast', 'studio']),
  e('📡', 'Satellite Antenna', 'objects', ['satellite', 'antenna', 'signal']),
  e('🔋', 'Battery', 'objects', ['battery', 'power', 'charge']),
  e('🪫', 'Low Battery', 'objects', ['battery', 'low', 'empty']),
  e('🔌', 'Electric Plug', 'objects', ['plug', 'electric', 'charge']),
  e('💡', 'Light Bulb', 'objects', ['bulb', 'light', 'idea', 'bright']),
  e('🔦', 'Flashlight', 'objects', ['flashlight', 'torch', 'light']),
  e('🕯️', 'Candle', 'objects', ['candle', 'light', 'flame']),
  e('🧯', 'Fire Extinguisher', 'objects', ['fire extinguisher', 'safety']),
  e('🛢️', 'Oil Drum', 'objects', ['oil', 'drum', 'barrel']),
  e('💸', 'Money with Wings', 'objects', ['money', 'fly', 'spend', 'waste']),
  e('💵', 'Dollar Banknote', 'objects', ['money', 'dollar', 'bill', 'cash']),
  e('💴', 'Yen Banknote', 'objects', ['money', 'yen', 'japan']),
  e('💶', 'Euro Banknote', 'objects', ['money', 'euro', 'europe']),
  e('💷', 'Pound Banknote', 'objects', ['money', 'pound', 'british']),
  e('🪙', 'Coin', 'objects', ['coin', 'money', 'change']),
  e('💰', 'Money Bag', 'objects', ['money', 'bag', 'rich', 'dollar']),
  e('💳', 'Credit Card', 'objects', ['credit card', 'payment', 'money']),
  e('💎', 'Gem Stone', 'objects', ['diamond', 'gem', 'jewel', 'precious']),
  e('⚖️', 'Balance Scale', 'objects', ['scale', 'balance', 'justice', 'law']),
  e('🪜', 'Ladder', 'objects', ['ladder', 'climb', 'step']),
  e('🧰', 'Toolbox', 'objects', ['toolbox', 'tools', 'fix']),
  e('🪛', 'Screwdriver', 'objects', ['screwdriver', 'tool', 'fix']),
  e('🔧', 'Wrench', 'objects', ['wrench', 'tool', 'fix']),
  e('🔨', 'Hammer', 'objects', ['hammer', 'tool', 'build']),
  e('⚒️', 'Hammer and Pick', 'objects', ['hammer', 'pick', 'mine']),
  e('🛠️', 'Hammer and Wrench', 'objects', ['tools', 'build', 'fix', 'settings']),
  e('⛏️', 'Pick', 'objects', ['pick', 'mine', 'dig']),
  e('🪚', 'Carpentry Saw', 'objects', ['saw', 'cut', 'wood']),
  e('🔩', 'Nut and Bolt', 'objects', ['nut', 'bolt', 'hardware']),
  e('⚙️', 'Gear', 'objects', ['gear', 'settings', 'cog', 'mechanical']),
  e('🗜️', 'Clamp', 'objects', ['clamp', 'compress', 'vice']),
  e('🔗', 'Link', 'objects', ['link', 'chain', 'url', 'connect']),
  e('⛓️', 'Chains', 'objects', ['chain', 'link', 'lock']),
  e('🪝', 'Hook', 'objects', ['hook', 'hang', 'fishing']),
  e('📎', 'Paperclip', 'objects', ['paperclip', 'office', 'attach']),
  e('🖇️', 'Linked Paperclips', 'objects', ['paperclip', 'link', 'attach']),
  e('📐', 'Triangular Ruler', 'objects', ['ruler', 'triangle', 'math']),
  e('📏', 'Straight Ruler', 'objects', ['ruler', 'measure', 'straight']),
  e('🧮', 'Abacus', 'objects', ['abacus', 'math', 'calculate']),
  e('📌', 'Pushpin', 'objects', ['pin', 'pushpin', 'location']),
  e('📍', 'Round Pushpin', 'objects', ['pin', 'location', 'map']),
  e('✂️', 'Scissors', 'objects', ['scissors', 'cut', 'tool']),
  e('🖊️', 'Pen', 'objects', ['pen', 'write', 'ballpoint']),
  e('🖋️', 'Fountain Pen', 'objects', ['pen', 'fountain', 'write']),
  e('✒️', 'Black Nib', 'objects', ['nib', 'pen', 'write']),
  e('🖌️', 'Paintbrush', 'objects', ['paint', 'brush', 'art']),
  e('🖍️', 'Crayon', 'objects', ['crayon', 'draw', 'color']),
  e('📝', 'Memo', 'objects', ['memo', 'note', 'write', 'pencil']),
  e('✏️', 'Pencil', 'objects', ['pencil', 'write', 'edit']),
  e('🔍', 'Magnifying Glass Tilted Left', 'objects', ['search', 'magnify', 'find', 'zoom']),
  e('🔎', 'Magnifying Glass Tilted Right', 'objects', ['search', 'magnify', 'find']),
  e('🔏', 'Locked with Pen', 'objects', ['locked', 'pen', 'secure', 'sign']),
  e('🔐', 'Locked with Key', 'objects', ['locked', 'key', 'secure']),
  e('🔒', 'Locked', 'objects', ['locked', 'secure', 'privacy', 'padlock']),
  e('🔓', 'Unlocked', 'objects', ['unlocked', 'open', 'padlock']),
  e('🔑', 'Key', 'objects', ['key', 'lock', 'password']),
  e('🗝️', 'Old Key', 'objects', ['key', 'old', 'vintage']),
  e('🔐', 'Locked with Key', 'objects', ['locked', 'key', 'secure']),
  e('🛡️', 'Shield', 'objects', ['shield', 'protect', 'defense', 'security']),
  e('🗡️', 'Dagger', 'objects', ['dagger', 'knife', 'weapon']),
  e('⚔️', 'Crossed Swords', 'objects', ['swords', 'battle', 'fight']),
  e('🔫', 'Water Pistol', 'objects', ['gun', 'water', 'pistol', 'squirt']),
  e('🪃', 'Boomerang', 'objects', ['boomerang', 'throw', 'return']),
  e('💣', 'Bomb', 'objects', ['bomb', 'explosive', 'danger']),
  e('🧨', 'Firecracker', 'objects', ['firecracker', 'dynamite', 'bang']),
  e('🪓', 'Axe', 'objects', ['axe', 'chop', 'wood']),
  e('🏠', 'House', 'objects', ['house', 'home']),
  e('📦', 'Package', 'objects', ['package', 'box', 'delivery', 'shipping']),
  e('📫', 'Closed Mailbox with Raised Flag', 'objects', ['mailbox', 'mail', 'letter']),
  e('📮', 'Postbox', 'objects', ['postbox', 'mail', 'letter']),
  e('📧', 'E-Mail', 'objects', ['email', 'mail', 'message', 'letter']),
  e('📩', 'Envelope with Arrow', 'objects', ['email', 'send', 'message']),
  e('📨', 'Incoming Envelope', 'objects', ['email', 'receive', 'inbox']),
  e('📄', 'Page Facing Up', 'objects', ['document', 'page', 'file']),
  e('📃', 'Page with Curl', 'objects', ['document', 'page', 'script']),
  e('📑', 'Bookmark Tabs', 'objects', ['bookmark', 'tabs', 'mark']),
  e('🗒️', 'Spiral Notepad', 'objects', ['notepad', 'spiral', 'notes']),
  e('📊', 'Bar Chart', 'objects', ['chart', 'bar', 'graph', 'stats']),
  e('📈', 'Chart Increasing', 'objects', ['chart', 'increase', 'growth', 'up']),
  e('📉', 'Chart Decreasing', 'objects', ['chart', 'decrease', 'down', 'loss']),
  e('📋', 'Clipboard', 'objects', ['clipboard', 'paste', 'document']),
  e('📁', 'File Folder', 'objects', ['folder', 'file', 'directory']),
  e('📂', 'Open File Folder', 'objects', ['folder', 'open', 'file']),
  e('🗄️', 'File Cabinet', 'objects', ['cabinet', 'file', 'archive']),
  e('🗑️', 'Wastebasket', 'objects', ['trash', 'delete', 'bin', 'waste']),
  e('📅', 'Calendar', 'objects', ['calendar', 'date', 'schedule']),
  e('📆', 'Tear-Off Calendar', 'objects', ['calendar', 'date', 'schedule']),
  e('🗓️', 'Spiral Calendar', 'objects', ['calendar', 'spiral', 'date']),
  e('📇', 'Card Index', 'objects', ['card index', 'rolodex']),
  e('🗃️', 'Card File Box', 'objects', ['card file', 'box', 'organize']),
  e('📖', 'Open Book', 'objects', ['book', 'read', 'open']),
  e('📚', 'Books', 'objects', ['books', 'library', 'read', 'study']),
  e('📕', 'Closed Book', 'objects', ['book', 'red', 'read']),
  e('📗', 'Green Book', 'objects', ['book', 'green', 'read']),
  e('📘', 'Blue Book', 'objects', ['book', 'blue', 'read']),
  e('📙', 'Orange Book', 'objects', ['book', 'orange', 'read']),
  e('📓', 'Notebook', 'objects', ['notebook', 'write', 'journal']),
  e('📔', 'Notebook with Decorative Cover', 'objects', ['notebook', 'decorative', 'journal']),
  e('📒', 'Ledger', 'objects', ['ledger', 'notebook', 'account']),
  e('🔖', 'Bookmark', 'objects', ['bookmark', 'tag', 'label']),
  e('🏷️', 'Label', 'objects', ['label', 'tag', 'price']),
  e('🔬', 'Microscope', 'objects', ['microscope', 'science', 'research']),
  e('🔭', 'Telescope', 'objects', ['telescope', 'space', 'astronomy', 'stars']),
  e('🧪', 'Test Tube', 'objects', ['test tube', 'science', 'experiment']),
  e('🧫', 'Petri Dish', 'objects', ['petri dish', 'science', 'biology']),
  e('🧬', 'DNA', 'objects', ['dna', 'gene', 'science', 'biology']),
  e('🩺', 'Stethoscope', 'objects', ['stethoscope', 'doctor', 'medical']),
  e('💊', 'Pill', 'objects', ['pill', 'medicine', 'drug']),
  e('🩹', 'Adhesive Bandage', 'objects', ['bandaid', 'bandage', 'heal']),
  e('🛁', 'Bathtub', 'objects', ['bathtub', 'bath', 'clean']),
  e('🚿', 'Shower', 'objects', ['shower', 'bath', 'clean']),
  e('🪥', 'Toothbrush', 'objects', ['toothbrush', 'teeth', 'clean']),
  e('🧹', 'Broom', 'objects', ['broom', 'sweep', 'clean']),
  e('🧺', 'Basket', 'objects', ['basket', 'laundry', 'picnic']),
  e('🧻', 'Roll of Paper', 'objects', ['toilet paper', 'roll', 'tissue']),
  e('🪣', 'Bucket', 'objects', ['bucket', 'pail', 'water']),
  e('🧴', 'Lotion Bottle', 'objects', ['lotion', 'sunscreen', 'cream']),
  e('🛎️', 'Bellhop Bell', 'objects', ['bell', 'hotel', 'service']),
  e('🧳', 'Luggage', 'objects', ['luggage', 'travel', 'suitcase']),
  e('🪞', 'Mirror', 'objects', ['mirror', 'reflection']),
  e('🪟', 'Window', 'objects', ['window', 'view']),
  e('🛏️', 'Bed', 'objects', ['bed', 'sleep', 'rest']),
  e('🪑', 'Chair', 'objects', ['chair', 'seat', 'sit']),
  e('🛋️', 'Couch and Lamp', 'objects', ['couch', 'sofa', 'lamp', 'living room']),
  e('🚪', 'Door', 'objects', ['door', 'entrance', 'exit']),
  e('🧸', 'Teddy Bear', 'objects', ['teddy bear', 'toy', 'stuffed', 'cute']),
  e('🪆', 'Nesting Dolls', 'objects', ['matryoshka', 'russian dolls', 'nesting']),
  e('🖼️', 'Framed Picture', 'objects', ['picture', 'frame', 'art']),
  e('🗺️', 'World Map', 'objects', ['map', 'world', 'travel']),
  e('🏮', 'Red Paper Lantern', 'objects', ['lantern', 'red', 'japanese', 'festival']),

  // ===== SYMBOLS =====
  e('❤️', 'Red Heart', 'symbols', ['love', 'heart', 'red']),
  e('🧡', 'Orange Heart', 'symbols', ['heart', 'orange', 'love']),
  e('💛', 'Yellow Heart', 'symbols', ['heart', 'yellow', 'love']),
  e('💚', 'Green Heart', 'symbols', ['heart', 'green', 'love']),
  e('💙', 'Blue Heart', 'symbols', ['heart', 'blue', 'love']),
  e('💜', 'Purple Heart', 'symbols', ['heart', 'purple', 'love']),
  e('🖤', 'Black Heart', 'symbols', ['heart', 'black', 'dark']),
  e('🤍', 'White Heart', 'symbols', ['heart', 'white', 'pure']),
  e('🤎', 'Brown Heart', 'symbols', ['heart', 'brown']),
  e('💔', 'Broken Heart', 'symbols', ['heartbreak', 'broken', 'sad']),
  e('❣️', 'Heart Exclamation', 'symbols', ['heart', 'exclamation']),
  e('💕', 'Two Hearts', 'symbols', ['love', 'hearts', 'couple']),
  e('💞', 'Revolving Hearts', 'symbols', ['love', 'hearts']),
  e('💓', 'Beating Heart', 'symbols', ['heartbeat', 'love']),
  e('💗', 'Growing Heart', 'symbols', ['heart', 'love', 'growing']),
  e('💖', 'Sparkling Heart', 'symbols', ['heart', 'sparkle', 'love']),
  e('💘', 'Heart with Arrow', 'symbols', ['cupid', 'heart', 'love']),
  e('💝', 'Heart with Ribbon', 'symbols', ['heart', 'gift', 'love']),
  e('☮️', 'Peace Symbol', 'symbols', ['peace', 'hippie']),
  e('✝️', 'Latin Cross', 'symbols', ['cross', 'christian', 'religion']),
  e('☪️', 'Star and Crescent', 'symbols', ['islam', 'muslim', 'star']),
  e('🕉️', 'Om', 'symbols', ['om', 'hindu', 'yoga', 'meditation']),
  e('☸️', 'Wheel of Dharma', 'symbols', ['dharma', 'buddhism']),
  e('✡️', 'Star of David', 'symbols', ['star of david', 'jewish']),
  e('☯️', 'Yin Yang', 'symbols', ['yin yang', 'balance', 'tao']),
  e('☦️', 'Orthodox Cross', 'symbols', ['orthodox', 'cross', 'christian']),
  e('🛐', 'Place of Worship', 'symbols', ['worship', 'religion', 'pray']),
  e('⛎', 'Ophiuchus', 'symbols', ['zodiac', 'ophiuchus']),
  e('♈', 'Aries', 'symbols', ['aries', 'zodiac', 'horoscope']),
  e('♉', 'Taurus', 'symbols', ['taurus', 'zodiac']),
  e('♊', 'Gemini', 'symbols', ['gemini', 'zodiac']),
  e('♋', 'Cancer', 'symbols', ['cancer', 'zodiac']),
  e('♌', 'Leo', 'symbols', ['leo', 'zodiac']),
  e('♍', 'Virgo', 'symbols', ['virgo', 'zodiac']),
  e('♎', 'Libra', 'symbols', ['libra', 'zodiac']),
  e('♏', 'Scorpio', 'symbols', ['scorpio', 'zodiac']),
  e('♐', 'Sagittarius', 'symbols', ['sagittarius', 'zodiac']),
  e('♑', 'Capricorn', 'symbols', ['capricorn', 'zodiac']),
  e('♒', 'Aquarius', 'symbols', ['aquarius', 'zodiac']),
  e('♓', 'Pisces', 'symbols', ['pisces', 'zodiac']),
  e('🆔', 'ID Button', 'symbols', ['id', 'identity']),
  e('⚛️', 'Atom Symbol', 'symbols', ['atom', 'science', 'physics']),
  e('🈳', 'Japanese "Vacancy" Button', 'symbols', ['japanese', 'vacancy', 'kanji']),
  e('🈹', 'Japanese "Discount" Button', 'symbols', ['japanese', 'discount', 'kanji']),
  e('☢️', 'Radioactive', 'symbols', ['radioactive', 'nuclear', 'danger']),
  e('☣️', 'Biohazard', 'symbols', ['biohazard', 'danger', 'toxic']),
  e('📴', 'Mobile Phone Off', 'symbols', ['phone', 'off', 'silent']),
  e('📳', 'Vibration Mode', 'symbols', ['vibrate', 'phone', 'silent']),
  e('🈶', 'Japanese "Not Free of Charge" Button', 'symbols', ['japanese', 'kanji']),
  e('🈚', 'Japanese "Free of Charge" Button', 'symbols', ['japanese', 'free', 'kanji']),
  e('🈸', 'Japanese "Application" Button', 'symbols', ['japanese', 'application', 'kanji']),
  e('🈺', 'Japanese "Open for Business" Button', 'symbols', ['japanese', 'open', 'kanji']),
  e('🈷️', 'Japanese "Monthly Amount" Button', 'symbols', ['japanese', 'monthly', 'kanji']),
  e('✴️', 'Eight-Pointed Star', 'symbols', ['star', 'eight pointed']),
  e('🆚', 'VS Button', 'symbols', ['versus', 'vs', 'fight']),
  e('💮', 'White Flower', 'symbols', ['flower', 'good job', 'japanese']),
  e('🉐', 'Japanese "Bargain" Button', 'symbols', ['japanese', 'bargain', 'kanji']),
  e('㊙️', 'Japanese "Secret" Button', 'symbols', ['japanese', 'secret', 'kanji']),
  e('㊗️', 'Japanese "Congratulations" Button', 'symbols', ['japanese', 'congratulations', 'kanji']),
  e('🈴', 'Japanese "Passing Grade" Button', 'symbols', ['japanese', 'pass', 'kanji']),
  e('🈵', 'Japanese "No Vacancy" Button', 'symbols', ['japanese', 'full', 'kanji']),
  e('🈲', 'Japanese "Prohibited" Button', 'symbols', ['japanese', 'prohibited', 'kanji']),
  e('🅰️', 'A Button (Blood Type)', 'symbols', ['a', 'blood type']),
  e('🅱️', 'B Button (Blood Type)', 'symbols', ['b', 'blood type']),
  e('🆎', 'AB Button (Blood Type)', 'symbols', ['ab', 'blood type']),
  e('🆑', 'CL Button', 'symbols', ['clear', 'cl']),
  e('🅾️', 'O Button (Blood Type)', 'symbols', ['o', 'blood type']),
  e('🆘', 'SOS Button', 'symbols', ['sos', 'help', 'emergency']),
  e('❌', 'Cross Mark', 'symbols', ['no', 'cancel', 'x', 'wrong', 'delete']),
  e('⭕', 'Hollow Red Circle', 'symbols', ['circle', 'o', 'correct']),
  e('🛑', 'Stop Sign', 'symbols', ['stop', 'sign', 'red']),
  e('⛔', 'No Entry', 'symbols', ['no entry', 'stop', 'forbidden']),
  e('📛', 'Name Badge', 'symbols', ['name', 'badge', 'id']),
  e('🚫', 'Prohibited', 'symbols', ['no', 'prohibited', 'forbidden', 'banned']),
  e('💢', 'Anger Symbol', 'symbols', ['anger', 'angry', 'mad']),
  e('♨️', 'Hot Springs', 'symbols', ['hot springs', 'onsen', 'steam']),
  e('🚷', 'No Pedestrians', 'symbols', ['no pedestrians', 'forbidden']),
  e('🚯', 'No Littering', 'symbols', ['no littering', 'clean']),
  e('🚳', 'No Bicycles', 'symbols', ['no bikes', 'forbidden']),
  e('🚱', 'Non-Potable Water', 'symbols', ['no drinking', 'water']),
  e('🔞', 'No One Under Eighteen', 'symbols', ['18+', 'adult', 'nsfw']),
  e('📵', 'No Mobile Phones', 'symbols', ['no phone', 'silent']),
  e('🔇', 'Muted Speaker', 'symbols', ['mute', 'silent', 'no sound']),
  e('🔈', 'Speaker Low Volume', 'symbols', ['speaker', 'low', 'sound']),
  e('🔉', 'Speaker Medium Volume', 'symbols', ['speaker', 'medium', 'sound']),
  e('🔊', 'Speaker High Volume', 'symbols', ['speaker', 'loud', 'sound']),
  e('🔔', 'Bell', 'symbols', ['bell', 'notification', 'ring']),
  e('🔕', 'Bell with Slash', 'symbols', ['bell', 'mute', 'silent']),
  e('📣', 'Megaphone', 'symbols', ['megaphone', 'announce', 'loud']),
  e('📢', 'Loudspeaker', 'symbols', ['loudspeaker', 'announce', 'loud']),
  e('💬', 'Speech Balloon', 'symbols', ['speech', 'chat', 'message', 'talk']),
  e('💭', 'Thought Balloon', 'symbols', ['thought', 'think', 'bubble']),
  e('🗯️', 'Right Anger Bubble', 'symbols', ['anger', 'speech', 'yell']),
  e('♠️', 'Spade Suit', 'symbols', ['spade', 'cards', 'poker']),
  e('♣️', 'Club Suit', 'symbols', ['club', 'cards', 'poker']),
  e('♥️', 'Heart Suit', 'symbols', ['heart', 'cards', 'poker']),
  e('♦️', 'Diamond Suit', 'symbols', ['diamond', 'cards', 'poker']),
  e('🃏', 'Joker', 'symbols', ['joker', 'cards', 'wild']),
  e('🀄', 'Mahjong Red Dragon', 'symbols', ['mahjong', 'game', 'chinese']),
  e('🎴', 'Flower Playing Cards', 'symbols', ['cards', 'hanafuda', 'japanese']),
  e('🔁', 'Repeat Button', 'symbols', ['repeat', 'loop', 'replay']),
  e('🔂', 'Repeat Single Button', 'symbols', ['repeat', 'one', 'loop']),
  e('▶️', 'Play Button', 'symbols', ['play', 'start', 'forward']),
  e('⏸️', 'Pause Button', 'symbols', ['pause', 'stop', 'wait']),
  e('⏹️', 'Stop Button', 'symbols', ['stop', 'square']),
  e('⏺️', 'Record Button', 'symbols', ['record', 'circle', 'red']),
  e('⏭️', 'Next Track Button', 'symbols', ['next', 'skip', 'forward']),
  e('⏮️', 'Last Track Button', 'symbols', ['previous', 'back', 'rewind']),
  e('⏩', 'Fast-Forward Button', 'symbols', ['fast forward', 'skip']),
  e('⏪', 'Fast Reverse Button', 'symbols', ['rewind', 'back']),
  e('🔀', 'Shuffle Tracks Button', 'symbols', ['shuffle', 'random']),
  e('🔃', 'Clockwise Vertical Arrows', 'symbols', ['refresh', 'reload', 'sync']),
  e('🔄', 'Counterclockwise Arrows Button', 'symbols', ['refresh', 'reload', 'sync']),
  e('⬆️', 'Up Arrow', 'symbols', ['up', 'arrow', 'north']),
  e('⬇️', 'Down Arrow', 'symbols', ['down', 'arrow', 'south']),
  e('⬅️', 'Left Arrow', 'symbols', ['left', 'arrow', 'west']),
  e('➡️', 'Right Arrow', 'symbols', ['right', 'arrow', 'east']),
  e('↗️', 'Up-Right Arrow', 'symbols', ['arrow', 'northeast']),
  e('↘️', 'Down-Right Arrow', 'symbols', ['arrow', 'southeast']),
  e('↙️', 'Down-Left Arrow', 'symbols', ['arrow', 'southwest']),
  e('↖️', 'Up-Left Arrow', 'symbols', ['arrow', 'northwest']),
  e('↕️', 'Up-Down Arrow', 'symbols', ['arrow', 'up down']),
  e('↔️', 'Left-Right Arrow', 'symbols', ['arrow', 'left right']),
  e('🔙', 'BACK Arrow', 'symbols', ['back', 'arrow', 'return']),
  e('🔚', 'END Arrow', 'symbols', ['end', 'arrow']),
  e('🔛', 'ON! Arrow', 'symbols', ['on', 'arrow']),
  e('🔜', 'SOON Arrow', 'symbols', ['soon', 'arrow']),
  e('🔝', 'TOP Arrow', 'symbols', ['top', 'arrow']),
  e('🔘', 'Radio Button', 'symbols', ['radio', 'button', 'circle']),
  e('🔳', 'White Square Button', 'symbols', ['square', 'button', 'white']),
  e('🔲', 'Black Square Button', 'symbols', ['square', 'button', 'black']),
  e('⚪', 'White Circle', 'symbols', ['circle', 'white', 'round']),
  e('⚫', 'Black Circle', 'symbols', ['circle', 'black', 'round']),
  e('🔴', 'Red Circle', 'symbols', ['circle', 'red', 'round']),
  e('🟠', 'Orange Circle', 'symbols', ['circle', 'orange']),
  e('🟡', 'Yellow Circle', 'symbols', ['circle', 'yellow']),
  e('🟢', 'Green Circle', 'symbols', ['circle', 'green']),
  e('🔵', 'Blue Circle', 'symbols', ['circle', 'blue']),
  e('🟣', 'Purple Circle', 'symbols', ['circle', 'purple']),
  e('🟤', 'Brown Circle', 'symbols', ['circle', 'brown']),
  e('🟥', 'Red Square', 'symbols', ['square', 'red']),
  e('🟧', 'Orange Square', 'symbols', ['square', 'orange']),
  e('🟨', 'Yellow Square', 'symbols', ['square', 'yellow']),
  e('🟩', 'Green Square', 'symbols', ['square', 'green']),
  e('🟦', 'Blue Square', 'symbols', ['square', 'blue']),
  e('🟪', 'Purple Square', 'symbols', ['square', 'purple']),
  e('🟫', 'Brown Square', 'symbols', ['square', 'brown']),
  e('⬛', 'Black Large Square', 'symbols', ['square', 'black', 'large']),
  e('⬜', 'White Large Square', 'symbols', ['square', 'white', 'large']),
  e('◼️', 'Black Medium Square', 'symbols', ['square', 'black', 'medium']),
  e('◻️', 'White Medium Square', 'symbols', ['square', 'white', 'medium']),
  e('🔶', 'Large Orange Diamond', 'symbols', ['diamond', 'orange']),
  e('🔷', 'Large Blue Diamond', 'symbols', ['diamond', 'blue']),
  e('🔸', 'Small Orange Diamond', 'symbols', ['diamond', 'orange', 'small']),
  e('🔹', 'Small Blue Diamond', 'symbols', ['diamond', 'blue', 'small']),
  e('🔺', 'Red Triangle Pointed Up', 'symbols', ['triangle', 'red', 'up']),
  e('🔻', 'Red Triangle Pointed Down', 'symbols', ['triangle', 'red', 'down']),
  e('◽', 'White Medium-Small Square', 'symbols', ['square', 'white']),
  e('◾', 'Black Medium-Small Square', 'symbols', ['square', 'black']),
  e('✅', 'Check Mark Button', 'symbols', ['check', 'yes', 'done', 'complete', 'correct']),
  e('☑️', 'Check Box with Check', 'symbols', ['checkbox', 'check', 'done']),
  e('✔️', 'Check Mark', 'symbols', ['check', 'yes', 'correct']),
  e('❎', 'Cross Mark Button', 'symbols', ['no', 'x', 'wrong']),
  e('➕', 'Plus', 'symbols', ['plus', 'add', 'math']),
  e('➖', 'Minus', 'symbols', ['minus', 'subtract', 'math']),
  e('➗', 'Division', 'symbols', ['divide', 'division', 'math']),
  e('✖️', 'Multiply', 'symbols', ['multiply', 'times', 'math']),
  e('♾️', 'Infinity', 'symbols', ['infinity', 'forever', 'loop']),
  e('‼️', 'Double Exclamation Mark', 'symbols', ['exclamation', 'double', 'bang']),
  e('⁉️', 'Exclamation Question Mark', 'symbols', ['exclamation', 'question']),
  e('❓', 'Red Question Mark', 'symbols', ['question', 'what', 'why']),
  e('❔', 'White Question Mark', 'symbols', ['question', 'what']),
  e('❕', 'White Exclamation Mark', 'symbols', ['exclamation', 'warning']),
  e('❗', 'Red Exclamation Mark', 'symbols', ['exclamation', 'warning', 'important']),
  e('〰️', 'Wavy Dash', 'symbols', ['wavy', 'dash', 'line']),
  e('💱', 'Currency Exchange', 'symbols', ['currency', 'exchange', 'money']),
  e('💲', 'Heavy Dollar Sign', 'symbols', ['dollar', 'money', 'price']),
  e('⚕️', 'Medical Symbol', 'symbols', ['medical', 'health', 'hospital']),
  e('♻️', 'Recycling Symbol', 'symbols', ['recycle', 'green', 'environment']),
  e('⚜️', 'Fleur-de-lis', 'symbols', ['fleur de lis', 'french', 'scout']),
  e('🔱', 'Trident Emblem', 'symbols', ['trident', 'spear', 'poseidon']),
  e('📛', 'Name Badge', 'symbols', ['name', 'badge']),
  e('🔰', 'Japanese Symbol for Beginner', 'symbols', ['beginner', 'japanese', 'new']),
  e('⭕', 'Hollow Red Circle', 'symbols', ['circle', 'o']),
  e('✅', 'Check Mark Button', 'symbols', ['check', 'done', 'yes']),
  e('☑️', 'Check Box with Check', 'symbols', ['checkbox', 'done']),
  e('✔️', 'Check Mark', 'symbols', ['check', 'correct']),
  e('©️', 'Copyright', 'symbols', ['copyright', 'c', 'legal']),
  e('®️', 'Registered', 'symbols', ['registered', 'r', 'trademark']),
  e('™️', 'Trade Mark', 'symbols', ['trademark', 'tm', 'brand']),
  e('#️⃣', 'Keycap: #', 'symbols', ['hash', 'number', 'pound']),
  e('*️⃣', 'Keycap: *', 'symbols', ['star', 'asterisk']),
  e('0️⃣', 'Keycap: 0', 'symbols', ['zero', '0', 'number']),
  e('1️⃣', 'Keycap: 1', 'symbols', ['one', '1', 'number']),
  e('2️⃣', 'Keycap: 2', 'symbols', ['two', '2', 'number']),
  e('3️⃣', 'Keycap: 3', 'symbols', ['three', '3', 'number']),
  e('4️⃣', 'Keycap: 4', 'symbols', ['four', '4', 'number']),
  e('5️⃣', 'Keycap: 5', 'symbols', ['five', '5', 'number']),
  e('6️⃣', 'Keycap: 6', 'symbols', ['six', '6', 'number']),
  e('7️⃣', 'Keycap: 7', 'symbols', ['seven', '7', 'number']),
  e('8️⃣', 'Keycap: 8', 'symbols', ['eight', '8', 'number']),
  e('9️⃣', 'Keycap: 9', 'symbols', ['nine', '9', 'number']),
  e('🔟', 'Keycap: 10', 'symbols', ['ten', '10', 'number']),
  e('🏧', 'ATM Sign', 'symbols', ['atm', 'bank', 'money']),
  e('🚮', 'Litter in Bin Sign', 'symbols', ['trash', 'bin', 'litter']),
  e('🚰', 'Potable Water', 'symbols', ['water', 'drinking']),
  e('♿', 'Wheelchair Symbol', 'symbols', ['wheelchair', 'accessibility', 'disabled']),
  e('🚹', 'Men\'s Room', 'symbols', ['mens', 'bathroom', 'restroom']),
  e('🚺', 'Women\'s Room', 'symbols', ['womens', 'bathroom', 'restroom']),
  e('🚻', 'Restroom', 'symbols', ['restroom', 'bathroom', 'wc']),
  e('🚼', 'Baby Symbol', 'symbols', ['baby', 'changing', 'nursery']),
  e('🚾', 'Water Closet', 'symbols', ['wc', 'bathroom', 'restroom']),
  e('ℹ️', 'Information', 'symbols', ['info', 'information', 'help']),

  // ===== FLAGS =====
  e('🏁', 'Chequered Flag', 'flags', ['finish', 'race', 'checkered', 'flag']),
  e('🚩', 'Triangular Flag', 'flags', ['flag', 'red', 'warning', 'red flag']),
  e('🎌', 'Crossed Flags', 'flags', ['flags', 'crossed', 'japanese']),
  e('🏴', 'Black Flag', 'flags', ['flag', 'black', 'pirate']),
  e('🏳️', 'White Flag', 'flags', ['flag', 'white', 'surrender']),
  e('🏳️‍🌈', 'Rainbow Flag', 'flags', ['rainbow', 'pride', 'lgbtq', 'gay']),
  e('🏳️‍⚧️', 'Transgender Flag', 'flags', ['transgender', 'trans', 'pride', 'flag']),
  e('🏴‍☠️', 'Pirate Flag', 'flags', ['pirate', 'flag', 'skull']),
  e('🇺🇸', 'Flag: United States', 'flags', ['usa', 'america', 'us', 'united states']),
  e('🇬🇧', 'Flag: United Kingdom', 'flags', ['uk', 'britain', 'england', 'united kingdom']),
  e('🇨🇦', 'Flag: Canada', 'flags', ['canada', 'maple']),
  e('🇦🇺', 'Flag: Australia', 'flags', ['australia', 'aussie']),
  e('🇫🇷', 'Flag: France', 'flags', ['france', 'french']),
  e('🇩🇪', 'Flag: Germany', 'flags', ['germany', 'german']),
  e('🇮🇹', 'Flag: Italy', 'flags', ['italy', 'italian']),
  e('🇪🇸', 'Flag: Spain', 'flags', ['spain', 'spanish']),
  e('🇯🇵', 'Flag: Japan', 'flags', ['japan', 'japanese']),
  e('🇰🇷', 'Flag: South Korea', 'flags', ['korea', 'south korea', 'korean']),
  e('🇨🇳', 'Flag: China', 'flags', ['china', 'chinese']),
  e('🇮🇳', 'Flag: India', 'flags', ['india', 'indian']),
  e('🇧🇷', 'Flag: Brazil', 'flags', ['brazil', 'brazilian']),
  e('🇲🇽', 'Flag: Mexico', 'flags', ['mexico', 'mexican']),
  e('🇷🇺', 'Flag: Russia', 'flags', ['russia', 'russian']),
  e('🇿🇦', 'Flag: South Africa', 'flags', ['south africa']),
  e('🇳🇬', 'Flag: Nigeria', 'flags', ['nigeria', 'nigerian']),
  e('🇪🇬', 'Flag: Egypt', 'flags', ['egypt', 'egyptian']),
  e('🇸🇦', 'Flag: Saudi Arabia', 'flags', ['saudi arabia', 'saudi']),
  e('🇦🇪', 'Flag: United Arab Emirates', 'flags', ['uae', 'emirates', 'dubai']),
  e('🇹🇷', 'Flag: Turkey', 'flags', ['turkey', 'turkish']),
  e('🇮🇱', 'Flag: Israel', 'flags', ['israel', 'israeli']),
  e('🇸🇪', 'Flag: Sweden', 'flags', ['sweden', 'swedish']),
  e('🇳🇴', 'Flag: Norway', 'flags', ['norway', 'norwegian']),
  e('🇩🇰', 'Flag: Denmark', 'flags', ['denmark', 'danish']),
  e('🇫🇮', 'Flag: Finland', 'flags', ['finland', 'finnish']),
  e('🇳🇱', 'Flag: Netherlands', 'flags', ['netherlands', 'dutch', 'holland']),
  e('🇧🇪', 'Flag: Belgium', 'flags', ['belgium', 'belgian']),
  e('🇨🇭', 'Flag: Switzerland', 'flags', ['switzerland', 'swiss']),
  e('🇦🇹', 'Flag: Austria', 'flags', ['austria', 'austrian']),
  e('🇵🇱', 'Flag: Poland', 'flags', ['poland', 'polish']),
  e('🇵🇹', 'Flag: Portugal', 'flags', ['portugal', 'portuguese']),
  e('🇬🇷', 'Flag: Greece', 'flags', ['greece', 'greek']),
  e('🇮🇪', 'Flag: Ireland', 'flags', ['ireland', 'irish']),
  e('🇸🇬', 'Flag: Singapore', 'flags', ['singapore']),
  e('🇹🇭', 'Flag: Thailand', 'flags', ['thailand', 'thai']),
  e('🇻🇳', 'Flag: Vietnam', 'flags', ['vietnam', 'vietnamese']),
  e('🇵🇭', 'Flag: Philippines', 'flags', ['philippines', 'filipino']),
  e('🇮🇩', 'Flag: Indonesia', 'flags', ['indonesia', 'indonesian']),
  e('🇲🇾', 'Flag: Malaysia', 'flags', ['malaysia', 'malaysian']),
  e('🇳🇿', 'Flag: New Zealand', 'flags', ['new zealand', 'kiwi']),
  e('🇦🇷', 'Flag: Argentina', 'flags', ['argentina', 'argentinian']),
  e('🇨🇱', 'Flag: Chile', 'flags', ['chile', 'chilean']),
  e('🇨🇴', 'Flag: Colombia', 'flags', ['colombia', 'colombian']),
  e('🇵🇪', 'Flag: Peru', 'flags', ['peru', 'peruvian']),
  e('🇺🇦', 'Flag: Ukraine', 'flags', ['ukraine', 'ukrainian']),
  e('🇷🇴', 'Flag: Romania', 'flags', ['romania', 'romanian']),
  e('🇭🇺', 'Flag: Hungary', 'flags', ['hungary', 'hungarian']),
  e('🇨🇿', 'Flag: Czechia', 'flags', ['czech', 'czechia']),
  e('🇭🇷', 'Flag: Croatia', 'flags', ['croatia', 'croatian']),
  e('🇰🇪', 'Flag: Kenya', 'flags', ['kenya', 'kenyan']),
  e('🇪🇹', 'Flag: Ethiopia', 'flags', ['ethiopia', 'ethiopian']),
  e('🇬🇭', 'Flag: Ghana', 'flags', ['ghana', 'ghanaian']),
  e('🇲🇦', 'Flag: Morocco', 'flags', ['morocco', 'moroccan']),
  e('🇵🇰', 'Flag: Pakistan', 'flags', ['pakistan', 'pakistani']),
  e('🇧🇩', 'Flag: Bangladesh', 'flags', ['bangladesh', 'bangladeshi']),
  e('🇱🇰', 'Flag: Sri Lanka', 'flags', ['sri lanka']),
  e('🇳🇵', 'Flag: Nepal', 'flags', ['nepal', 'nepali']),
  e('🇹🇼', 'Flag: Taiwan', 'flags', ['taiwan', 'taiwanese']),
  e('🇭🇰', 'Flag: Hong Kong SAR China', 'flags', ['hong kong']),
  e('🇶🇦', 'Flag: Qatar', 'flags', ['qatar']),
  e('🇰🇼', 'Flag: Kuwait', 'flags', ['kuwait']),
  e('🇯🇴', 'Flag: Jordan', 'flags', ['jordan']),
  e('🇱🇧', 'Flag: Lebanon', 'flags', ['lebanon']),
  e('🇮🇶', 'Flag: Iraq', 'flags', ['iraq']),
  e('🇮🇷', 'Flag: Iran', 'flags', ['iran']),
  e('🇦🇫', 'Flag: Afghanistan', 'flags', ['afghanistan']),
  e('🇨🇺', 'Flag: Cuba', 'flags', ['cuba']),
  e('🇯🇲', 'Flag: Jamaica', 'flags', ['jamaica']),
  e('🇵🇷', 'Flag: Puerto Rico', 'flags', ['puerto rico']),
  e('🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Flag: England', 'flags', ['england', 'british']),
  e('🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Flag: Scotland', 'flags', ['scotland', 'british']),
  e('🏴󠁧󠁢󠁷󠁬󠁳󠁿', 'Flag: Wales', 'flags', ['wales', 'british']),
];

export function applySkinTone(emoji: string, modifier: string): string {
  if (!modifier) return emoji;
  // Insert skin tone modifier after the first code point
  const codePoints = [...emoji];
  if (codePoints.length === 0) return emoji;
  return codePoints[0] + modifier + codePoints.slice(1).join('');
}

export function getEmojiCodepoint(emoji: string): string {
  return [...emoji].map(c => 'U+' + c.codePointAt(0)!.toString(16).toUpperCase().padStart(4, '0')).join(' ');
}

export function getHtmlEntity(emoji: string): string {
  return [...emoji].map(c => '&#x' + c.codePointAt(0)!.toString(16).toUpperCase() + ';').join('');
}

export function getUnicodeEscape(emoji: string): string {
  return [...emoji].map(c => '\\u{' + c.codePointAt(0)!.toString(16).toUpperCase() + '}').join('');
}

export function getCssContent(emoji: string): string {
  return [...emoji].map(c => '\\' + c.codePointAt(0)!.toString(16).toUpperCase()).join('');
}

export function getShortcode(name: string): string {
  return ':' + name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '') + ':';
}
